---
author: 
  - name: João Paulo Pereira Barros
    url:  http://lattes.cnpq.br/0351156693555523
    orcid: 0000-0001-7680-576X
    email: joaopaulobarros@ufc.br
    affiliations: 
      - name: Federal University of Ceará    
  - name: Érica Atem Gonçalves de Araújo Costa
    url: http://lattes.cnpq.br/7397272595520801
    orcid: 0000-0002-4341-8138
    email: ericaatem@ufc.br
    affiliations: 
      - name: Federal University of Ceará
  - name: Carla Jéssica de Araújo Gomes
    url: http://lattes.cnpq.br/9684612126688971
    orcid: 0000-0002-6979-2646
    email: carlajessicagomes@alu.ufc.br
    affiliations: 
      - name: Federal University of Ceará
  - name: Emanuel Meireles Vieira
    url: http://lattes.cnpq.br/4122228867993191
    orcid: 0000-0002-7346-4944
    email: emanuelmeireles@ufc.br
    affiliations: 
      - name: Federal University of Ceará
filters:
  - section-bibliographies
bibliography: barros_podcast.bib
reference-section-title: References
---

# Podcasts on Psychology, Human Rights, and Contemporary Socio-Psychological Processes: Experiences of VIESES-UFC During the Pandemic

## Introduction

This chapter aims to report the experiences of creating podcasts, as communication products, by VIESES: Group of Research and Interventions on Violence, Social Exclusion, and Subjectivation, between 2020 and 2021, as strategies for dialogical production and sharing knowledge about Psychology, human rights, and contemporary socio-psychological processes during the COVID-19 pandemic. This laboratory is part of the Department of Psychology and the Graduate Program in Psychology at the Federal University of Ceará (UFC).

The COVID-19 pandemic brought several challenges to the academic activities of VIESES, which, since its creation, occurred through the insertion and joint composition in peripheral territories of Fortaleza. With the implementation of emergency remote activities at UFC to ensure physical distancing for the prevention of COVID-19 infections, it was necessary to reinvent formative strategies that maintained the dialogical ethos of our knowledge production in Psychology, both at the undergraduate and graduate levels [@barros2023festival].

The experiences of creating 4 podcasts by VIESES within this context will be reported: Presentemente, #TraçandoVáriosPlanos, Artes Insurgentes, and Café da Tarde. The goal of these initiatives was for knowledge production, in a scenario of extreme fragility in guaranteeing rights, to act politically for visibility, articulation, and production of other channels of listening to an insurgent psychology [@barros2019violencias]. The aim was, above all, to act against the historical-social logics of oppression, aggravated by the pandemic context, and to serve as a tool that blurs hegemonic boundaries of knowledge construction, using cybernetic tools to overcome these challenges.

## Presentemente Podcast

::: column-margin
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/show/3jPwBGXDgvmx5ANZ8i49vR?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy">

</iframe>
:::

The Presentemente podcast, whose name is inspired by the song “Sujeito de Sorte” by singer Belchior, was created in 2020 with the aim of pluralizing and resonating discussions about the present from critical and diverse perspectives on topics pertinent to the field of human rights, valuing practices of resistance and ways of staying "sane, safe, and strong." The project was made possible by a VIESES team composed of undergraduate students and a faculty advisor, involving topic selection, contacting guests[^barros_podcast-1], script creation, editing, posting episodes on podcast aggregators, and promoting artwork on social media. The discussions in each episode are conducted by people affected in various ways by the topic, either from experience in social movements, academic productions, or life experiences, aiming to diversify the debates and elucidate various perspectives. Each episode, averaging 50 minutes, was released biweekly on Thursdays between July and October 2020. The first season of the podcast consists of six episodes. The titles covered, in order of publication, were: “Hatred and Cancellation Today,” “Racism and Anti-Racist Struggle,” “Peripheries and Poetic Re-Existences,” “LGBTQIA+ Lives and LGBTFOBIA,” and “Childhoods in Brazil.” The season finale was an extra episode titled “Mental Health and Youth from the Periphery: Psychosocial Distress and Care Production in the Pandemic Context,” resulting from a podcast episode submitted to the XI International Symposium on Brazilian Youth (JUBRA) held in December 2020.

[^barros_podcast-1]: Here and elsewhere in the text, we adopt non-binary language to avoid reiterating hegemonic and homogeneous sex-gender dynamics for those who help us build our research, extension, and training networks.

The second season of the Presentemente podcast is still in progress. Four episodes have been released, from July to September 2021, on the themes of “Arts and Peripheries on the Agenda” and “Cultural Appropriation and Colonialities,” with the third and fourth episodes being two parts of the same conversation titled “Indigenous Peoples in Brazil.”

## #TraçandoVáriosPlanos Podcast

::: column-margin
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/show/3p5ws64FIsufDxcY7TnPnp?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy">

</iframe>
:::

The #TraçandoVáriosPlanos podcast, which dialogues with the song “Sulamericano” by the Bahian musical group BaianaSystem, focuses on Social Psychology and Political Psychology readings on contemporary socio-psychological themes and processes. More than 14 episodes were released between 2020 and 2021, across the first two seasons. The production of #TraçandoVáriosPlanos always involves the participation of the advising professor or teaching internship students in the presentation, as well as guests from the academic context. All episodes, averaging 40 minutes, are available for free on YouTube on the Pós-PsicologiaS UFC channel and also on Spotify.

The released episodes covered themes such as: “Psychosocial Aspects of Violence and Social Psychology”; “Neoliberalism and the Necroeconomy of Punishment: Racism, Mass Incarceration, and Pandemic Impacts”; “Social Psychology and Hate Speech Today”; “Critical Criminology, Feminist Criminology, and the Problem of Punitive Penal Selectivity”; “Neoliberal Subjectivation and Social Psychology”; “Social Transformations of Violence and Prison Dynamics: The Case of Ceará”; “Beyond Prison: Alternative Penal Policy or Alternative to Penal Policy?”; “Intersectionality, Production of Subjectivities, and Social Psychology”; “Gender and Subjectivity from Feminist Studies”; and “Can the White Listen? – Reflections on Whiteness”; “Social Psychology and Inequalities in the COVID-19 Pandemic”; “Psychology and Extremisms Today”; “Psychosocial Aspects of Racism and Anti-Racist Psychology”; and “Denialism and the Public Dimension of Mourning in the Pandemic: Connections Between Subjectivity and Politics.”

In 2022, a special season on Psychology and Human Rights was produced. Its 12 episodes came from panels held during an extension course on this theme promoted by VIESES in 2021.

#TraçandoVáriosPlanos has proven to be an important strategy for maintaining and enhancing the connection of students with the Psychology course at UFC by offering learning and reflection alternatives in the face of reality and challenges posed by social distancing, being fundamental to expanding the reach of themes debated by VIESES far beyond its student body through new communication and information tools.

## Artes Insurgentes Podcast

::: column-margin
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/show/3KRu4KITQ4leFp6bOk4O5h?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy">

</iframe>
:::

From the articulation and partnership of students from the Psychology course and the Graduate Program in Psychology, members of the Laboratory of Psychology in Subjectivity and Society (LAPSUS) and VIESES, both linked to UFC, with support from UFC's Artistic Culture Promotion Program, the project “Artes Insurgentes: Collectivizing Resistances” was founded. Aimed at encouraging insurgent practices and strengthening the cultural memory of urban peripheries by enhancing the artistic-cultural expressions of youth collectives from the neighborhoods of Grande Bom Jardim (GBJ), in Fortaleza-CE[^barros_podcast-2], the project has shown a significant social role in peripheral territories, especially with students from public schools and members of youth collectives from GBJ. Since the first semester of 2021, one of the project's action fronts has been producing a podcast to disseminate and dialogue with members of actions, activities, and projects within youth collectives that fight for rights in GBJ and use art as a tool of struggle, from various artistic language expressions, such as visual arts, literature, music, dance, and theater.

[^barros_podcast-2]: Grande Bom Jardim encompasses the neighborhoods of Bom Jardim, Granja Portugal, Canindezinho, and Siqueira, from the former V Administrative Region of Fortaleza/CE.

So far, the podcast, titled “Artes Insurgentes: Collectivizing Resistances,” has three episodes ranging from 20 to 50 minutes, available on Spotify. The first episode consists of a presentation of the project and its proposals; the second episode addresses issues related to the 2021 Youth Festival and its repercussions for the local scene; and the third episode, the most recent, discusses actions taken by the Specialized Technical Articulation Nucleus (Narte) of the Bom Jardim Cultural Center and its resonances in the GBJ community.

In 2022, the first episode of the Artes Insurgentes podcast, titled “Resistances and Alliances in the Breaks,” was released, addressing how residents of the Grande Bom Jardim region participated in political and social movements related to combating violence and fighting for human rights in their territories in the city.

## Café da Tarde Podcast

::: column-margin
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/2RIrwphBaPZ5LFyF4sup6g?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy">

</iframe>
:::

The Café da Tarde podcast, linked to VIESES and carried out as an action of the Welcome and Retention Program (UFC), is named after the reference to encounters that arise in daily university life, to conversations between students, and between students and professors that fill the gaps and traverse the rigid institutional routine and its imprisoning logics.

During 2020, four episodes were produced, averaging 50 minutes, inspired by teaching, extension, and research practices (university tripod) as experienced by the student community (undergraduate and graduate) in the pandemic context. Aiming to promote welcoming actions at the university in times of weakened ties and attacks on public education, the Café da Tarde podcast sought to constitute, in the virtual environment, exchanges where everyday affections, student experiences, affective places, and processes of invention and sharing were invoked as forms of alliance and resistance to discouragement, understood as the political sentiment of our time.

The conversations included the following triggering themes: the university in times of remote learning, inventive ways of doing extension when it is not possible to be “in the field”; the implications and challenges of conducting research during the current health crisis; and the creative process of the podcast as a UFC project. The 12 guests were undergraduate and graduate students from the UFC Psychology course. The podcast was carried out by undergraduate students and the advising professor from VIESES. We highlight that the search for a sound and visual aesthetic (posts to promote the podcast) that allowed for erasures, intervals, silences, and interruptions was an ethical-aesthetic-political bet against neoliberal and productivity-driven models in Brazilian higher education. Not only that, it was a way to inhabit the virtual territory in the face of the imminent massification of distance education strategies within the university as a horizon of control over teaching-learning processes.

## Final Considerations

The above-listed communication products are contemporary productions that effectively address Psychology through collective and engaged technical production with social movements, productions that resonate their practices and impact the practice of Psychology, expanding content, debate, and involving communities, faculty, and students. Thus, modes of knowledge production are reinvented, encouraging and valuing practices that highlight challenges and impasses in the decolonization of Psychology [@miranda2022subjetividades].

The creation of these technical productions, in the context of the COVID-19 pandemic and the rise of neo-fascist values and practices, started from the premise that addressing the multifaceted field of Human Rights through innovative strategies that broaden the reach and resonance of technical productions in Psychology is fundamental for promoting critical training in this area, linking undergraduate and graduate studies, ethically committed to transforming unequal realities in the Brazilian context, which still coexists with strong marks and practices of coloniality [@ballestrin2013america; @lugones2014rumo]. To move against uncritical and reductionist approaches on the subject, the communication products could address realities and theoretical references of thinkers in Psychology and related fields that problematize cis-hetero-patriarchal-colonial-capitalist patterns [@silva2023aliancas].

We believe that these technical productions linked to VIESES are relevant for enhancing, strengthening, and stimulating reflections and experience reports on tackling inequalities, violence, and oppression in Brazil [@benicio2018necropolitica]. Furthermore, they have sought to contribute, within the scope of emergency remote teaching, to meeting society's demands for elucidating sociopsychological aspects of violence and sharing successful experiences in defending human rights. These products have innovation potential, as they sought to create more interactive channels for discussion, re-elaboration, and dissemination of knowledge produced by VIESES-UFC research. The number of editions also shows the potential for replicating actions. The fact that the podcasts have been accessed by people in various countries shows their international reach. The articulations between undergraduate, graduate students, faculty, professionals, and members of social movements, as well as the need for the team to appropriate methods and techniques of curation, scripting, editing, and dissemination, demonstrate the high complexity of such technical productions.

Therefore, it is believed that these communication products contribute to expanding the impact of the Graduate Program in Psychology at UFC on society by enhancing the resonances of discussions that have been dear to VIESES since its creation. This is because, with the podcasts, these problematizations could reach from undergraduate and graduate students to professionals, whether in Psychology or related fields, to public policy managers and members of collectives, social movements, and civil society organizations from different regions of Brazil and even beyond the national territory.
