---
author: 
  - name: Érica Atem Gonçalves de Araújo Costa
    url: http://lattes.cnpq.br/7397272595520801
    orcid: 0000-0002-4341-8138
    email: ericaatem@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Eliandra Estevam Abreu
    url: http://lattes.cnpq.br/7383332877315017
    orcid: 0009-0003-6822-9848
    email: eliandraestevam.ufc@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Vitor Batista de Melo
    url: http://lattes.cnpq.br/3596023702275982
    orcid: 0009-0003-3866-2341
    email: vitorbdmelo@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Laryssa Ferreira Rabelo
    url: http://lattes.cnpq.br/8693665760616962
    orcid: 0009-0001-5241-3611
    email: rabelolaryssa05@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Milena Araújo Bezerra
    url: http://lattes.cnpq.br/8279997683731267
    orcid: 0000-0002-2589-7876
    email: milenaaraujo@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Ingrid Rabelo Freitas
    url: http://lattes.cnpq.br/1658652947743069
    orcid: 0000-0002-8365-6245
    email: ingrid.rbfreitas@gmail.com
    affiliations: 
      - name: Centro de Defesa da Vida Herbert de Souza
  - name: Rogério da Costa Araújo
    url: http://lattes.cnpq.br/7431158482111778
    orcid: 0000-0003-3508-362X
    email: rio.costa50@gnail.com
    affiliations: 
      - name: Centro de Defesa da Vida Herbert de Souza
  - name: João Paulo Pereira Barros
    url: http://lattes.cnpq.br/0351156693555523
    orcid: 0000-0001-7680-576X
    email: joaopaulobarros@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará

filters:
  - section-bibliographies
bibliography: costa_interv_criancas.bib
reference-section-title: References
---

# Psychosocial interventions with children and adolescents in urban peripheral territories

## Introduction

This chapter describes and analyzes psychosocial interventions with children and adolescents in an urban periphery of Fortaleza, Ceará. It is written by many hands - students, professors, and social articulators - aligning with the commitment to listen to a plurality of voices that ethically bring us closer to the social complexity of ways of existence in various territories. The practices in focus were carried out between 2019 and 2020 and are related to the project Maquinarias: Infâncias em Invenção, part of university extension in Social Psychology, linked to the research and study group on Violence, Social Exclusion, and Subjectivation (VIESES) and the Department of Psychology of the Federal University of Ceará (UFC).

Since 2019, through the articulation with the NGO Centro de Defesa da Vida Herbert de Souza (CDVHS), the Extension Project Maquinarias: Infâncias em Invenção has been hosted by the Centro de Cidadania e Valorização Humana (CCVH) in the Nova Canudos occupation, in the Canindezinho neighborhood. Given the demand for actions, projects, and activities with children in this area, we built participatory methodologies as experiences that strengthen them as political subjects in the community. Additionally, the actions also emerge from the possibility of conducting training and research activities with children in a peripheral context. During the first year, a group entitled "Invenções das Crianças de Nova Canudos" was consolidated, composed on average of twenty-two (22) children, mostly black, poor, and public school students aged between 6 and 12 years, as well as researchers, students, articulators, and social movement activists, residents of the occupation.

In 2020, the demand, made explicit at the beginning of the partnership, persisted and expanded due to the children's need to:

a.  maintain the bond, which gained specificity in a pandemic context;
b.  effectively contribute to the structural improvement of the CCVH, a space recognized and conquered by them to carry out activities of their interest; and
c.  organize the group and their modes of participation and action, leading movements that fight for a better life in Nova Canudos.

All these demands were crossed by the collective analysis of what was possible to do virtually, given the worsening social inequalities, directly related to the children's access to social networks. At the same time, other desires were being mobilized and resisted the erasure generated by the naturalization of the precariousness of life in a peripheral context. This created flows for experiments in the audiovisual production scope of children on YouTube, TikTok, and WhatsApp.

We start the text by relating peripheral territorialities and modes of subjectivation, as well as repositioning problems and ways of doing. Next, we address the conditions of insertion in the field from a cartographic and procedural perspective, as well as the joint creation of the existential territory in which inter(in)ventive and participatory actions with children and adolescents from the Nova Canudos occupation are forged. These actions are articulated with the CCVH, which not only hosts but is also invented in the political agency of children and adolescents. Finally, we highlight ways of doing (group device) that draw the field of forces of this existential territory, emphasizing the challenges of conducting demands collectively.

## Peripheral territorialities and modes of subjectivation: acting starts by knowing how to invent other problems

From what place do we speak? With whom do we articulate these interventions highlighted here? What knowledge is constructed with Nova Canudos? These questions guide us in writing this topic, beginning by highlighting the narratives of residents and social articulators about this community, as well as socioeconomic indicators present in documents about the neighborhood that come to life in exchanges with children and adolescents.

Nova Canudos was born in 1993 as a popular occupation influenced by the Base Ecclesial Communities (CEBs), a movement of the Catholic church oriented by Liberation Theology that tried to link faith and life in pastoral actions. This is because one of the strong issues in the lives of many families in the 1990s in Fortaleza was precisely access to land in the city to guarantee the right to housing. Thus, with the support of the local church, the land was occupied, and the land plots were informally organized. In these, an area was reserved to build a local facility for religious celebrations and community problem discussions. This area gave rise to the Centro de Cidadania e Valorização Humana (CCVH), which is still maintained today as a reference for collective activities carried out in Nova Canudos. In another area, another community center was built with the support of a project called Mãos Unidas, in which volunteer doctors provided care for the population. This facility was incorporated into the basic health care network and is now home to the Abner Cavalcante Brasil Basic Health Unit, the only public health post in the Special Zone of Social Interest (ZEIS) of Bom Jardim, which serves Nova Canudos and other residents of neighboring communities.

Nova Canudos is located in the Canindezinho neighborhood, which, until 2020, was one of the neighborhoods in the Greater Bom Jardim (GBJ) region. As of municipal law no. 278 of 2019, which establishes a new regionalization in the city of Fortaleza, and decree no. 14.590 of 2020, the Canindezinho neighborhood became part of the Regional Executive Secretariat - SER X, being separated from what officially became considered GBJ - SER V [@fortalezaEntendaNova]. The area has high indicators of urban violence and concentrations of poverty and extreme poverty, with a population of 211 thousand inhabitants, according to the Census - IBGE (2010). Given the state's neglect, popular political articulation became strong, which explains the engagement of residents, from children to - especially - young people and adults, in resident associations, non-governmental organizations (NGOs), collectives, and other instruments that allow their participation in the process of organizing, mobilizing, and overseeing public policies aimed at the periphery. Among these articulations present in GBJ, we highlight the action of the Centro de Defesa da Vida Herbert Souza (CDVHS).

Given the ethical-political commitment to confronting the processes of vulnerabilization of children's lives, combined with the recognition of participation practices and community organization historically carried out in GBJ, Nova Canudos became an empowered peripheral territory, open to jointly problematizing the relationships between children and modes of participation, in a contextualized perspective integrated with the children's movements in the community, highlighting the fact that they are the target audience of the activities carried out and hosted by the CCVH.

In this context, a Decolonial Social Psychology [@barros2017politica; @barros2019violencias; @mayorga2014contribuicoes], as a network of knowledge, supports the actions of Maquinarias: Infâncias em Invenção and is eventful between the university and peripheries. Events hold the potency of institutions that can denaturalize and produce breaches in the rigid perceptions of the social fabric and materialize in a racist, sexist, classist, heteronormative, and adult-centric web. Therefore, in this work, peripheries and universities are not given, ready, and finished places, but mutually constitute themselves through combined strategies and strive to denaturalize historical relations of distance and colonization.

This partnership, on which we now focus, can reposition social stigmas around the urban peripheries of Fortaleza, in line with the notion that these territories are plural and centers of life production, constantly disputing with hegemonic narratives of disqualification and criminalization. From this perspective, it has been possible to articulate children from different peripheral realities by integrating them into activities of other partner projects, creating records (photographs and videos) of children's collective action, and participating in public calls to maintain activities, with greater visibility of their ways of life, outside of stereotyped views that minimize their participation in the city. Thus, clues are produced that help denaturalize conceptions of childhood historically constituted in a colonial past, establishing them as a developmental condition that must go through schooling processes and family protection for the full exercise of citizenship [@castro2013infancia; @sarmento2013sociologia; @junior2020nocao].

Repositioning oneself ethically, aesthetically, and politically operates the invention of other problems with which to move thought. Being WITH complicates ways of acting, requiring negotiations, dialogues, and exchanges in which power-knowledge relations can have their effects analyzed, in order not to corroborate the historical silencing of subalternized classes, which, intersectionally, produce gender, generation, class, and ethnicity/race oppressions. In these two years of action, we have composed some clues for producing situated and implicated problems with which we have (un)learned: a) the need for articulation with territory agents, strengthening struggles and paths built collectively; b) the need for network monitoring of children and adolescents, paying attention to the constantly renewed trust bonds with them and their guardians; c) openness to experience and methodological creativity to carry out non-directed activities that respond to the collective agency of children and the singularization of their processes and demands.

## Conditions of field insertion from a cartographic perspective

Maquinarias arrived in 2019 in the territory of Greater Bom Jardim (GBJ) through partnership bonds between social actors and VIESES. These actors, members of the CDVHS, were responsible for building and partially maintaining the bridge that has extended between Maquinarias and CCVH for 2 years. In this community space in Nova Canudos, there were already occasional activities promoted by and for residents, such as capoeira and theater classes, craft workshops for making bracelets, and, not rarely, religious celebrations that mobilized different generational groups. Despite the lack of state assistance, the space remained active and reverberated the effects of collective actions by residents, integrating into the community network in Nova Canudos as a support point for cultural, training, and assistance activities for the population.

This organization signaled the CCVH's openness to the proposition and collective construction of activities with children and adolescents, making it possible for expectations, methodology, and objectives to emerge as an effect of the meetings. This perspective materialized and resonated with the inter(in)ventive and participatory action proposal that the extension project aspired to outline and put into practice [@dacosta2020reexistencias].

On the first visit to the CCVH, with the mediation of CDVHS articulators, Maquinarias found, in addition to a resident and member of the association's board of directors, ten children who, curious about the movement, approached and opened the way, without ceasing to "evaluate" the visitors. In this movement of getting to know and inventing each other, children, articulators, extensionists, and researchers set out to join, following an unforeseen flow, piece by piece, the gears of a new collective in the territory. The name forged for this group by the children themselves, still in the first meeting, "Invenções das Crianças de Nova Canudos," became quite indicative of how intervention, participation, and (micro)political agency intertwined to consolidate ways of creating, mapping, and processually accompanying an existential territory [@barros2009cartografar]. In their propositions, the children tension adult-centric models of action, centered on the FOR, and shift them to a doing WITH, articulating and creating spaces to fulfill their demands, besides inhabiting the community center while (re)inventing it.

The very insertion of Maquinarias in this existential territory showed itself as a continuous movement, of renewed attempts and conquests of the group's trust and acceptance, which did not remain static either due to the arrival of new children, their growth, or posture changes. Similarly, the extension project renewed itself through new cycles and commitments between fields of action and the university. These changes impacted the composition of forces and affective ties that mutually constitute Maquinarias and the Nova Canudos collective, understood as group, inter(in)ventive devices, and therefore effects of daily insurgencies, woven in encounters with children and adolescents. Thus, taking cartography as a research and intervention method, university extension activities are combined with the analytical process of a complex reality that occurs in the field, from the implication of extensionists and social articulators in collectively invented actions that produce problems, making the production of knowledge and practice inseparable [@dacosta2020reexistencias; @passos2009cartografia].

The fact that we consider the processuality that accompanies these bonds - university and periphery, Invenções and Maquinarias, children and extensionists, and many others - brings visibility to important factors, such as:

a.  the geographical distances that mainly adults traveled to reach the meetings and how these distances - the places to which each belongs - influence how each one connects, highlighting different conditions of vulnerabilities and social privileges;
b.  the context of the COVID-19 pandemic, which has persisted since the beginning of the second year of the collective's existence, with all its obstacles, such as the impossibility of face-to-face meetings, unequal access to the internet, and the worsening social vulnerability conditions that permeate the group; and
c.  the context of urban violence that surrounds the Nova Canudos occupation. This moving map requires, therefore, the insertion in the field as an attitude and not just a fixed pact, with positions delimited and defined prior to the very process of linking.

The inhabited territory, therefore, was never given, nor was a flag planted in the corner of the CCVH yard, or any other place that Invenções occupied, claiming Maquinarias' permanence in that location. It is, however, the confluence of desires and demands that circulate the collective that ties its members and establishes a continuous flow of activities, whether virtual or face-to-face.

## "Inventions of the children of Nova Canudos": actions of an intergenerational collective

A fundamental question seems to us to resume at this point in the text: the fact that the psychosocial interventions in focus here were carried out in the alternation between different creative processes, being the result of collective agencies, which we mapped in their subjectivation effects, without neutralities and/or hierarchical relations. They have marks that we consider potent for actions that place themselves micropolitically in the face of collective and community processes, which directly touch the challenges of political participation in intergenerational groups. Let’s see:

a.  Openness to improvisation;
b.  Availability for creation and experimentation without closed scripts;
c.  Interest in using and researching materials that favor diverse ways of participation, not necessarily linked to oral discourse;
d.  Interest in working with groups and willingness to do things together, in order to distance oneself from a specialist (expert) posture.

Thus, the "WITH children and adolescents" becomes a trigger for the joint planning of content, materials, places, process records, forms of dissemination, and effects for the group and the community.

We understand openness not only to differentiation but also to the group's becomings and, consequently, to the processuality and heterogeneity of field actions as a way of intervening in the complexity of group agencies [@barros2007grupo]. Extensionists and researchers move themselves and the field, faced with the proposal to produce WITH the children and learn from the encounters, also facing the challenge of conducting demands collectively. We bet that this (ethical) posture is close to that defined by the cartography of subjectivation processes, that is: an existential territory is produced by engaging in daily and collectively invented experiences [@alvarez2009cartografar].

The group's composition is diverse in terms of age, class, race, and gender markers, with children being able to move between meetings, with the number of participants varying from 15 to 20. This way of being together tensions conceptions of collectives and subjects that are homogeneous and fixed by an identity ideal, understanding a multiplicity of ways of collectively composing that can happen in each field of forces [@barros2007grupo].

### Actions in 2019: invention of a group device

The actions in the first year, totaling 16 meetings, established being and doing together as a device, with Invenções being a strategy to be seen not only in the community by other generational groups (family members, church group members, and social movement articulators) and by their peers but also in other territories. Additionally, acting collectively and being heard mobilized the children's desire for two types, both playful and free, of activity: situated, carried out biweekly at the CCVH headquarters, and displaced, carried out in city tours. We will see that in 2020, due to other space-time relations caused by the COVID-19 pandemic, the actions were described in a way that these conditions were made visible.

The meetings held at the CCVH included drawing workshops; making toys from recyclable materials; movie screenings; collective mapping of places where children circulate in the city; and semester start and end celebrations.

The children's periodic presence at the CCVH mobilized the association's board to ensure a space for the Invenções group to store productions, materials used, toys, among other needs. This achievement resulted from negotiating the common use of the space with other groups, fostering the participation and visibility of children in the community. Moreover, actions WITH the children became continuous in the territory, not just occasional.

City tours and visits to other places in Fortaleza allowed the children to encounter the public dimension of the city that is often denied to them by the walls of social exclusion and urban socio-spatial inequalities. Moving through Fortaleza, beyond Nova Canudos, aligned with the children's desire and happened through the invitation that Invenções received to participate in two events: the "II Colorindo O Gênero," a program that is part of the "Curta o Gênero," annually promoted by the NGO Fábrica de Imagens: ações educativas em cidadania e gênero, and the 2019 edition held at the Centro Dragão do Mar de Arte e Cultura; and the "International Children's Theater Festival of Ceará" (TIC), with theatrical performances at the Centro Cultural do Grande Bom Jardim (CCBJ), both facilities of the Ceará State Culture Secretariat (SECULT-CE). The lack of information on how to access public facilities (theater, cinema, parks, museums), in addition to the personal circumstances that hinder each one, often distances them from the possibility of using them. Thus, the movements experienced by the children problematize feelings of belonging to the city and the possibilities it offers.

Being able to move around the city with the children, besides being their desire, proved to be an activity of enormous impact and an important analyzer of the existing boundaries in the city, which invisibilize people living in peripheral territories. These are daily naturalized boundaries that need to be transformed. In this sense, the described tours were powerful opportunities to symbolically and concretely move our way of being in the territories, understood as a vector producing subjectivities.

### Actions in 2020: recomposition of movements amid the pandemic

The COVID-19 pandemic crossed the compositions of university extension and the Invenções das Crianças de Nova Canudos group, impacting temporalities and ways of accompanying and narrating collective actions. In this context, participation in the public call launched by the Centro Cultural do Grande Bom Jardim (CCBJ) with resources from the Poverty Combating Fund (FECOP) enabled the group to remain active and resistant in its collective actions during 2020.

Invenções das Crianças de Nova Canudos took on the dimension of a project and was awarded in the said Edital, in which children, social articulators, and Maquinarias members were proponents, resulting in cost support for maintaining the activities carried out and strengthening our ties with other neighborhood facilities. The proposition of activities occurred in line with collective demands, implying interventions at the CCVH headquarters, such as purchasing equipment, painting, repairs, and mobilization for cleaning and maintaining the headquarters.

During this period, due to the impossibility of holding face-to-face meetings, movements in social networks were fertilized, interconnecting everyday experiences through exchanges and shares. Despite the pandemic, strengthening bonds, making, and inventing WITH the children continued as our ethical horizon. Therefore, the meetings began to take place through the Google Meet platform, with the WhatsApp group being the space for daily conversations, action agreements, emergence, and sharing of ideas, listening to demands and interests, becoming, thus, a new territory to explore and build. Considering the undemocratic access to the internet and specific demands, we managed to hold some face-to-face meetings, respecting care protocols to prevent the spread of COVID-19. The monitoring of these activities and the mobilization for them to occur took place continuously, almost daily.

We call virtual actions those that focused on themes of interest to children and adolescents, as well as those related to the capillarization of their participation in virtual events:

-   "I Virtual Drawing Exhibition of Maquinarias";
-   "Meeting to talk about YouTube usage";
-   "Collective book readings";
-   "Participation in III Colorindo O Gênero"; and
-   "Participation in the 30th Anniversary Live of the Child and Adolescent Statute".

The virtual drawing exhibition mobilized us amid the daily life of social isolation, keeping us connected through free expression and each one's situation at the moment. The drawings were exhibited on the projects' and CCVH's social networks. The workshop on the relationships between children and YouTube usage, held in partnership with the Laboratory for Research on Relations Between Childhood, Youth, and Media (LABGRIM), linked to the Institute of Culture and Art/ICA of UFC, emerged from the children's experiments to create YouTube channels and the desire to talk about their inspirations and goals. From this, it was possible to create a moment to reflect on content production for/on the platform, image exposure, inspirations, and most accessed channels, self-care, and safety.

Moments to experience reading collectively proved to be powerful, from the expectation of the meeting, through the playful and participatory dimension assumed by the group members. Exchanging perceptions and meanings about the work was a reason for joy, despite the difficulties imposed by low-quality connections and access modes, usually made via cell phones. During mobilizations around the 30th anniversary of the Child and Adolescent Statute (ECA), one of the Invenções girls participated in a live event promoted by the Ceará Children's Rights Defense Forum (Fórum DCA Ceará), expressing her views on racism and the challenges of the pandemic, as well as reciting two self-authored poems.

A second set of activities resulted from articulations in the territory, with members of the extension and research team, CDVHS articulators, and the Local, Integrated, and Sustainable Development Network (Rede Dlis), and with the children themselves, namely:

-   "Distribution of masks and WHO guideline booklet";
-   "Distribution of 'Invenções e Distração' kits";
-   "Two cinema sessions at CCVH";
-   "Mutirão de limpeza no CCVH"; and
-   "Audiovisual course".

All activities required face-to-face meetings, possible at specific times during the COVID-19 pandemic - the presence of these moments was also due to the need to listen to the children's coping modes and their mental health. The theme of self-care and care for others, as a collective issue, permeated the activities of sharing information about the new coronavirus's spread and the territory and country's situation. Thus, the group established itself as a health promotion device, directly related to the children's experiences, doubts, difficulties, and ideas raised as a collective.

## Final considerations

The psychosocial interventions described and analyzed in this text emerged from the joint accompaniment and proposition of activities with an intergenerational group, including children of different ages, adults, and young residents of the Fortaleza periphery, as well as social articulators and extensionists. The work requires mediation, implication, and continuous active listening to the children, demanding flexibility and methodological creativity.

Its elaboration characterizes a sensitive, ethical, and contextualized work, through the construction and maintenance of spaces where the exercise of the right to participation by children is real. The collective production of knowledge repositions the university, leaving the imposing place of the center to occupy the place of sharing, of implicated thinking, as one of the forces that produce a common space. From this perspective, learning with the "Invenções das Crianças de Nova Canudos" decolonizes the research field on children's social participation and strengthens the effects of their actions on community life and public policies impacting peripheral contexts in Fortaleza.

We hope that the shared tracks and trails can inspire other actors and territories, once ethically oriented by the interest in creating conditions for children's participation from their life contexts and daily lives, as well as an invitation to experience creativity and methodological diversity linked to listening to children and adolescents and the desires they mobilize for changes in the social body.
