---
author: 
  - name: Rita Helena Sousa Ferreira Gomes
    url: http://lattes.cnpq.br/9324470543610163
    orcid: 0000-0002-2306-4264
    email: ritahelenagomes@ufc.br
    affiliations: 
      - name: Federal University of Ceará    
  - name: Iratan Bezerra de Sabóia
    url: http://lattes.cnpq.br/4256908254336676
    orcid: 0000-0003-3312-9954
    email: iratan@ufc.br
    affiliations: 
      - name: Federal University of Ceará
  - name: Ana Cecília Carenina Machado Mourão
    url: http://lattes.cnpq.br/2253638238142434
    orcid: 0000-0002-8569-224X
    email: ceciliamachadoodontologia@gmail.com
    affiliations: 
      - name: Federal University of Ceará
  - name: Ana Késia Silva Faustino
    url: http://lattes.cnpq.br/8679020802878119
    orcid: 0009-0003-3873-9214
    email: kesia.faustino.2000@gmail.com
    affiliations: 
      - name: Federal University of Ceará
  - name: Andressa da Silva Rodrigues
    url: https://lattes.cnpq.br/5221958688837066
    orcid: 0009-0009-2196-3694
    email: andressa20srodrigues@gmail.com
    affiliations: 
      - name: Federal University of Ceará
  - name: Giovana Freitas Oliveira
    url: http://lattes.cnpq.br/8034420553210047
    orcid: 0009-0005-0351-6517
    email: giovanaoll@alu.ufc.br
    affiliations: 
      - name: Federal University of Ceará
  - name: José Edberto Gadelha Rocha Júnior
    url: http://lattes.cnpq.br/9629710554359470
    orcid: 0000-0002-6660-1728
    email: edbertojunior.psi@gmail.com
    affiliations: 
      - name: Federal University of Ceará
  - name: Vitória Brandão de Lima Borges
    url: http://lattes.cnpq.br/8527436760147224
    orcid: 0009-0005-9397-1547
    email: vitoriabrandao66@gmail.com
    affiliations: 
      - name: Unifametro
filters:
  - section-bibliographies
bibliography: gomes_polifonias.bib
reference-section-title: References
---

# Polyphonies: Transdisciplinarity, Scientific Dissemination, and Dialogue in Action

## Introduction

Much has been discussed about the apparent gap between scientific knowledge and society. During the pandemic[^gomes_polifonias-1], and even before it, we observed a resurgence of anti-scientific manifestations such as anti-vaccine movements, the return of flat earth beliefs, and the use of unproven medications for disease treatment. Similarly, institutions producing academic knowledge, such as schools, universities, and scientific communicators, have not succeeded in maintaining a dialogue with society. Often, the language used does not facilitate communication, and the use of jargon incomprehensible to the majority of the "lay" population creates an insurmountable barrier for those outside the academic sphere. While technical teaching still prevails in the academic environment, transdisciplinarity and dialogue emerge as a way to bridge academic-scientific knowledge with reality, cultural experiences, and individuals' knowledge, allowing for enrichment and learning fundamental for the improvement of both dimensions without denying their specificities.

[^gomes_polifonias-1]: Here we refer to the emergence of SARS-CoV-2, which caused the COVID-19 pandemic in Brazil since March 2020.

This chapter aims to present aspects that traverse and compose the Polyphonies extension project, highlighting both its practices, which generally characterize as a technical production of the “Event Organization” type, and the main theoretical guidelines that underpin them. To this end, the chapter is subdivided into 2 sections, respectively:

1.  Introducing the project and its activities; and
2.  Pointing out conceptual elements of transdisciplinarity, dialogue, and scientific dissemination relevant to the said extension activity.

At the end, besides concisely revisiting the discussed points, some challenges for improving Polyphonies activities are listed.

## Getting to Know the Polyphonies Project

Polyphonies is an extension project of the Federal University of Ceará – Sobral Campus, which is based on the importance of transversal, transdisciplinary, decolonized, and transformative teaching that transcends the university's barriers. Only through the democratization of knowledge is it possible to contribute to mitigating vulnerabilities, training more ethical professionals aware of their responsibility to the general community, and ensuring that different social actors actively participate in knowledge production. Thus, Polyphonies' main objective is to disseminate scientific and philosophical knowledge using simple and accessible language that facilitates the approach and dialogue between academic and non-academic audiences.

Although it was registered with the Extension Pro-Rectory only in January 2020, the project originated from a meeting held on October 31, 2019, in the Mucambinho auditorium (UFC/Sobral). The event featured the participation of four PhD professors affiliated with UFC/Sobral to discuss the topic of "Time" from the perspectives of Music, with Dr. Adeline Stervinou; Physics, with Dr. João Guilherme Matias Nogueira; Engineering, with Dr. José Cláudio do Nascimento; and Anthropology, with Dr. Denise Silva. Despite the high level of the guests, they were asked to address the topic in a comprehensible and engaging way for an audience that included students and professors from various undergraduate and graduate courses. Each guest had between 10 and 15 minutes to speak, followed by an open session for audience comments and questions.

The event was very successful, with an estimated participation of 80 to 90 people, and it was evident that everyone (guests and audience) was interested in exchanging ideas and making transdisciplinary connections in a setting where informality and scientific rigor were perfectly balanced. Professors and students from seemingly different courses such as Music, Electrical Engineering, Computer Engineering, and Psychology engaged in deep and productive dialogues, momentarily forgetting their supposed disciplinary separation. The event's receptiveness was so strong that students, guests, and professors approached the organizers afterward to suggest other dialogue topics, demonstrating their desire for the activity's continuity. Consequently, plans began to take shape to ensure the event's regular occurrence and expand its reach beyond the university's walls.

Once registered with the proper authorities, the project's coordinators sought, in early March 2020, to establish a partnership with the Sobral Municipal Education Secretariat (SEDUC). The search for SEDUC was not random but reflected Polyphonies' commitment to extending beyond the university audience, provoking debates where multiple perspectives on a topic could flow. According to the plan, guests and school communities in basic education would have the chance to jointly create an environment for exchanges where the rigid marking of power and knowledge places would be continuously challenged.

SEDUC embraced the partnership proposal, understanding that it would bring to the municipality a relevant experience of transdisciplinary and dialogical practices in the regular school environment; a stimulus for studying subjects and curriculum content and academic reading through transdisciplinary topics that provoke logical and complex reasoning in an accessible manner, among other benefits. In return, the secretariat would assist in promoting the events within the school community, providing physical space and/or transportation to the event location, and financial support for publications derived from each meeting. However, on March 16, 2020, Sobral declared its first period of social isolation due to the SARS-CoV-2 (COVID-19) virus pandemic, postponing the developing plans with SEDUC until the health situation returned to normal.

It was then up to the newly formed Polyphonies team – 2 coordinating professors and 6 undergraduate students – like many other activities in various sectors, to reinvent planned actions for in-person delivery while maintaining the project's central aspects and ensuring everyone's health and safety. Considering the available possibilities and existing examples, the group opted to hold meetings online. Social networks and their popularity among different audiences emerged as a potentially interesting tool for achieving the project's goals under the imposed health scenario. The apparent simplicity of social networks, their reach, and the speed of content dissemination made them the primary source for promoting the 7 events that subsequently took place. Instagram, initially a photo-sharing social network, became for many a professional dissemination tool, for quick tutorials, and news. Thus, it was a virtual space suitable for the mobilizations and contacts desired by the project.

The Polyphonies project account on Instagram was created on May 30, 2020, as a place that gathered information about the project and its activities, also serving as a virtual interaction space with interested audiences, currently having 287 followers. Over time and with the team's maturation, the page also became a receptacle for posts with suggestions for artistic productions (series, books, films, and music) related to the theme of the most recent event. The choice of art was justified as an effective, democratic, and inviting dissemination form for the general public, mainly because its language is open to diverse views and subjectivity [@gomes2020artecontra]. Additionally, introducing art in dialogical mediation with the project's audience generated an initially unexpected product: Clubefonias, an action that gathers people of different age groups and realities via WhatsApp to discuss a work chosen by the members in biweekly meetings.

Besides the Instagram page and the Clubefonias WhatsApp group, the project created a YouTube channel in August 2020 that hosts the recorded events. On this widely accessible social network, 3 of the 7 organized meetings are available.

On June 16, 2020, the first virtual event took place via Google Meet, bringing together university professors with experience in Art, Philosophy, and Psychology and a representative of an African-based religion to discuss the theme "All Roads Lead to Knowledge." The theme was chosen by the Polyphonies team to introduce the project's proposal to the general public without appearing as a lecture and without imposing a limited way of thinking about knowledge. The idea was to indicate openness to dialogue and the project's transdisciplinary nature through the event title. During registration for the "live," participants were invited to suggest topics for future discussions, thus seeking to access their interests and realities. The event had 86 registrants, lasted 2 hours, and certificates were issued for guests and participants.

A few days after the inaugural event, the project team met to collectively evaluate the strengths and weaknesses to be improved in future actions. This moment proved essential and has since been incorporated into the extension group's meeting schedule. As a result of these event analyses, some modifications or action guidelines were implemented: ensuring space for audience questions/comments within the event time; reducing the meeting duration from 2 hours to 1 hour, considering the excess of virtual activities since the pandemic; decreasing the number of guests to 2 per session; creating 3 guiding questions distributed to the guests upon invitation, facilitating communication between different perspectives and their connection to everyday concerns; rotating the student team members as event moderators, as this contributes to their professional development; intensifying event promotion via WhatsApp and other means to reach more people outside the university; changing the event's name from "Round Table Discussion" to "Bar Talk."

The choice of the name "Bar Talk" deserves special attention, as it is linked to understanding that the "role of scientific dissemination has evolved over time, following the development of science and technology" [@albagli1996divulgacao]. In times of fast communication and social networks, it was considered important to adapt the name to the type of event held by Polyphonies. While "Round Table Discussion" conveys a dialogical and informal disposition, it also carries the image of an academic action common within school and university walls. However, "Bar Talk" evokes a space not associated with the scientific universe, and thus, it not only highlights the informality of the conversation and dialogue but also suggests active participation where discussions are accessible and stimulating. By distancing the events from a scientific dissemination praxis characterized by the difficulties of transmitting knowledge that academic and scientific circles display, the project reinforces openness to dialogue with other types of audiences and the opportunity to engage with various topics. Thus, scientific dissemination assumes essential roles in democratizing scientific knowledge and, consequently, opens doors to scientific literacy, contributing to including citizens in specialized topic debates that, even without many knowing, are intrinsically linked to and influence their lives [@bueno2010comunicacao], as well as adding to the education of so-called 'intellectuals' by giving them the chance to expand/exercise new languages and articulations from their expertise.

It is worth noting that the internal meetings of the Polyphonies team, held biweekly on Fridays, are important not only due to the "technical" decisions that arise from them. In fact, the group's meetings have served as a way to foster light and creative connections among participants, as most members did not have the chance to strengthen bonds in person, given that the pandemic began shortly after they joined the team. Approaching people virtually was the main challenge faced by the project, but the group's internal experience has been a successful example of how dialogical thinking and practice combined with transdisciplinarity are potent for building humanized and enriching social bonds.

Between March 16, 2020, and August 2021, when this chapter was written, Polyphonies conducted 7 events, bringing together 298 participants, including 16 guests (11 from academic backgrounds and 5 from non-academic backgrounds). In addition to the topic of the first meeting, already described, the subjects addressed were: Pandemic and family relationships; Contemporary work relationships; Art and social transformation; Fake news and its impacts on society; Social movements; Language – Norms, power, and social transformations. These themes, whenever possible, took into account the suggestions presented by the audience during event registration. To date, the project has recorded 17 topics brought by participants.

Despite this predominantly informative and practical description of the Polyphonies project, it is only possible to truly understand it by illuminating, albeit briefly, the theoretical and ethical pillars underlying its actions. This is the purpose of the next section.

## Theoretical and Ethical Pillars of Polyphonies

### Transdisciplinarity

Transdisciplinarity is understood as what is, at the same time, between, through, and beyond any discipline. The term, according to Guedes [-@guedes2010importancia], was first used by Piaget in 1970 but was only formalized in 1994 with the document "Charter of Transdisciplinarity" at the First World Congress in Portugal. Transdisciplinarity seeks to “transgress the logic of non-contradiction, articulating opposites: subject and object, subjectivity and objectivity, matter and consciousness, simplicity and complexity, unity and diversity” [@nicolescu1999manifesto; @santos2008complexidade]. In other words, transdisciplinarity understands that reality can be viewed integratively, blurring the boundaries between forms of knowledge and asserting that the whole – reality – is highly complex and integrated, and the parts – sciences, for instance – actively communicate and sustain each other. This approach breaks with the fixed and timeless idea of dichotomies, understanding them as interactive agents that must be considered from the relationships they establish among themselves. Thus, Santos [-@santos2008complexidade] states that "the understanding of reality ascends to another level, taking on a broader meaning and always open to new processes" (p. 5).

A serious analysis of the history of science reveals the transdisciplinary dimension of science, as scientific knowledge and society are intimately intertwined. The formation and consolidation of science point to a specific way of responding to society's questions and needs [@videira2004transdisciplinaridade].

Beyond this social rootedness, which shows that science is not external to the world, it is important to apply the transdisciplinary perspective to the very structure of science. While the departmentalization of science allows for undeniable advances through highly specialized studies, discoveries in each field and subfield of knowledge need to be repositioned within the complex web of reality that is not abstractly fragmented into study fields. In this sense, it is fundamental to recognize scientific knowledge as constituted by diverse professionals with diverse knowledges that relate and intersect. Thus, transdisciplinarity, by not disregarding the complex aspects of reality and valuing its multiplicity, enhances dialogue between science and society and between different spheres of scientific knowledge.

From this perspective, Martinazzo [-@martinazzo2020pensamento] suggests that transdisciplinarity is a better path to understanding a complex and multidimensional reality, as it uses mechanisms that enable adaptation to this multiplicity. Transdisciplinarity, by considering both the complex and the simple to comprehend reality, allows various fields to be contemplated in knowledge as they articulate in the world, making room for opposing ideas to be considered and for all fields of knowledge to exercise their importance.

Transdisciplinarity aims to overcome the closed universe produced by science by bringing forth the multiplicity of knowledge production modes and recognizing the importance of reintegrating the subject into the scientific observation process, given the strong interdependence between the observer, the observation process, and the observed object [@martinazzo2020pensamento, p.7].

Thus, transdisciplinarity, in its pursuit of knowledge reintegration and the subject's participation in scientific production, also facilitates the broader dissemination of knowledge, especially in societies where knowledge diffusion is often hindered by social inequalities, highlighting the elitist nature of knowledge access in these cultures. Indeed, this rapprochement is built because transdisciplinary practice strengthens the democratization of scientific knowledge by considering that this knowledge is produced for society and recognizing that non-scientific knowledge is relevant for understanding the world. Additionally, transdisciplinarity is linked to scientific dissemination, as it adapts to the complex and multidimensional reality, values contextualization, and creates an environment where divergent ideas and practices have the opportunity to be confronted respectfully and rigorously. Thus, transdisciplinarity fosters the dialogue essential for democratizing knowledge and genuinely democratic and free societies.

Having outlined the qualities and potentials of transdisciplinarity, the question remains: how can we promote transdisciplinary practices from the Brazilian university setting?

Clues to answering this question lie in the previously mentioned definition of transdisciplinarity, indicating the need to flexibilize knowledge boundaries through an integrated understanding of reality. Based on this, for scientific knowledge dissemination to occur, it is essential to devise strategies that ensure the traversal of physical and social barriers to knowledge access without neglecting the inherent possibilities of contemporary technologies. This is the arena where the Polyphonies Project operates with its events and actions.

The project's actions aim to address various contemporary issues from a contextualized and multifaceted perspective, understanding that even the simplest topic carries a multiplicity of information studied from plural theoretical and practical perspectives. Because they are plural, they can be approached from different references, giving the topic a transdisciplinary character. Let's take the first event, "All Roads Lead to Knowledge," as an example. As mentioned earlier, the meeting featured 4 guests, including 3 university professors (linked to Art, Psychology, and/or Philosophy) and a religious representative. On this occasion, each guest spoke about a type of knowledge related to their field (Art, Philosophy, Science, and Religion), highlighting not only their specificities but also their relationships with the other represented spheres. The event's transdisciplinary goal was successful, as the intertwined speeches of the guests effectively broke the traditional barriers between those knowledge fields, and the audience's participation through comments and questions gave/amplified the meaning of what was discussed while simultaneously glimpsing interaction points in the diverse speakers' discourses. In this first activity, the strength and, consequently, the need for transdisciplinary practices in scientific and non-scientific fields became evident as tools for enhancing the dissemination of knowledge integrated with society.

### Scientific Dissemination

Discussing scientific dissemination requires revisiting a few centuries to consider the very act of doing science. As highlighted by Moreira [-@moreira2002revolucao], the known scientific revolution occurred in the mid-17th century, influenced by various sociodemographic factors, bringing to the forefront many thinkers who are now scientific references, such as Kepler and Galileo. However, despite the growing recognition of scientific relevance and the development of technologies that expanded access to intellectual products, science remains in the hands of specific and small groups – albeit significantly larger and more diverse than in previous centuries – while most of the population remains ignorant of the scientific and technological knowledge production processes underlying the presented ways of life.

As previously mentioned, despite the many knowledge produced within research centers and university academies, their connection with the external public leaves much to be desired. The dissemination of what is produced usually does not reach those outside the scientific sphere, even though this seems to occur unintentionally, as nothing indicates that researchers are interested in this segregation. The problem of poor knowledge distribution has already concerned Lima Vaz [-@limavaz2000escritos], who emphasized:

> The great scientific revolutions of our century, while propelling technical progress, make the understanding of deep theoretical connections between scientific thought and technical practice more enigmatic to the common man, user of the objects that technology offers for his consumption and satisfaction. (p. 278).

One consequence of this poor knowledge distribution can be seen in today's anti-scientific movements, which, using resources that only exist due to the development of science and technology, propagate distorted and false information that fuels unfounded conspiracy theories with potentially devastating effects in politics, health, economy, environment, etc.

This reveals the urgency of rethinking the ways in which scientific knowledge dissemination has occurred – or failed to occur. More than ever, creating spaces where science and society can interact fluidly is essential. A fluid interaction capable of effectively disseminating academic knowledge requires always remembering that the audience addressed by the knowledge will consist of "lay" people. This implies considering not only the dissemination medium but also the language used.

Traditionally, sciences adopt a discourse type aimed at knowledge diffusion to a restricted audience. Thus, scientific communication among peers does not usually need to make concessions in its specialized discourse, as despite using restricted language, it finds its primary interlocutor in a very specific audience familiar with that vocabulary and data presentation form. However, when aiming to expand beyond those groups versed in academic jargon, scientists and intellectuals usually act believing, as Bueno [-@bueno2010comunicacao] points out, "that their audience shares the same concepts and that technical jargon constitutes common heritage" (p. 3). However, presuming that the chosen words for the discourse already carry specific meanings and functions cannot be dissociated from the notion that these meanings and functions take shape through contact with the listener. Therefore, in contact with individuals outside the scientific environment, words requiring a conception restricted to researchers' circles do not convey meanings [@authierrevuz2015dialogismo] and undermine the dissemination effort.

In this context, Polyphonies aims to practice scientific dissemination, understanding it as a process of recoding specialized discourse to make content accessible to a broad audience [@bueno2010comunicacao], an effort to translate and decode information shaped in academic-scientific codes and jargon into more familiar language understandable by the scientifically uneducated public [@bueno2010comunicacao]. The project assumes that knowledge dissemination is appropriate in "any activity of explaining and spreading knowledge, culture, and scientific and technical thought, under two conditions: outside official or equivalent education and without the aim of training specialists" [@marandino2002educacao, p. 5], and, based on this, proposes a colloquial conversation among different actors related to the selected event theme. In this interaction, driven by questions previously sent to the guests, researchers, practitioners (professionals, social movement participants, etc.), and the public have the chance to adjust and expand their different vocabularies, collectively weaving a glossary that harmonizes theories, practices, and experiences. Thus, the commitment to scientific dissemination results in a commitment to dialogue as a core pillar of Polyphonies.

### Dialogue

With the idea of dialogism, Mikhail Bakhtin shed light on the dialogical interactions that constitute and are woven between discourses, asserting that the dialogical relationship is constitutive of language [@marcuzzo2008dialogoinconcluso; @rechdan2003dialogismo]. According to him, humans must always be seen in their relationship with others, as "it is impossible to think of a person outside the relationships that bind them to others" [Faraco, 1996, as cited in @marcuzzo2008dialogoinconcluso, p. 4]. Thus, the dialogical dimension is not only present in language and discourses but continuously traverses our identity. Despite this foundational intertwining that links self and other, establishing dialogical relationships where one voice does not submit to others is not guaranteed a priori. Here, the notion of polyphony comes into play, pointing to a dialogical movement where "different social voices ... confront each other, clash, manifesting different social viewpoints on a given object ..." [@rechdan2003dialogismo, p. 46]. This concept aptly names the project: Polyphonies activities mobilize diverse social voices, creating an environment where distinct discourses have the opportunity to cross and consciously redraw themselves, recognizing their identities are not static or independent of their connection to the other.

As seen in the transdisciplinarity section, the project embraces the notion that knowledge construction operates multiply and constantly, encompassing different aspects that are shaped, transformed, or cease to be validated as they relate. This aligns with the idea that reality is complex, i.e., it does not have only one level, one side, one knowledge, all comprehensible definitively. From this angle, the hierarchicalization of knowledge or certain areas as less or more important loses a priori significance, as the engine and validation of knowledge are understood as inseparable from the flow of knowledge, experiences, and consequences at play.

Polyphonies' journey seeks to keep in mind that not only reality but also the individuals inhabiting and composing it are complex. Thus, in pursuing its commitment to having a transformative effect on the world, the project considers individuals as bearers of histories, experiences, and worldviews [@lucena2016dialogica]. Accordingly, Paulo Freire [-@freire2008medoeousadia] is an indispensable reference, understanding that "dialogue is, in itself, creative and re-creative" \[and that\] "dialogue seals the act of learning, which is never individual, although it has an individual dimension" (pp. 13-14). Adopting Freire's view, Polyphonies strives to convene, through dialogue, individuals as creative subjects endowed with unique riches, whose action/inaction impacts reality. By embedding dialogue as a core part of its activities, the project reinforces the idea that knowledge is a product of the collective of subjects who, consciously or not, invent and reinvent the world.

Therefore, considering scientific dissemination through dialogical lenses reaffirms the previously discussed need to subvert conventional relationships with language to create diverse spaces where words make sense for everyone. This task is especially challenging in a country with high social inequality and income concentration, requiring serious consideration that in formal lectures, congresses, or even classrooms, the language used can include or exclude subjects who have historically had their knowledge denied and erased by the imposition of a hegemonic culture, including scientific theories and institutions.

Chauí [-@chaui2002sereducador] invites us to take the next step, recalling that "democracy brings to the fore the problem of violence, that is, the reduction of the subject to the condition of a thing" (p. 68). In other words, by adopting dialogue as a form of scientific dissemination, Polyphonies is not simply concerned with the cosmetic dimension of language, making it palatable and accessible to those outside the academic milieu. More than that, the project's events aim to value the myriad ways individuals produce, signify, and narrate cultures and knowledge.

Thus, Polyphonies' actions counter a 'colonizing mission,' whose project was to homogenize the world, obliterating cultural differences. Through deeply anti-democratic and anti-dialogical colonization, much social experience was wasted, and the world's epistemological, cultural, and political diversity was reduced. Those who managed to survive colonizing advances were subjected to the dominant epistemological norm [@santos2008complexidade].

By establishing dialogue as an inescapable guideline for its activities, Polyphonies acknowledges the existence of a coloniality of knowledge and positions itself against it. Admitting that speech implies power relations means not shying away from repeatedly asking: Who speaks? To whom does one speak? About what does one speak? How does one speak? Which discursive practices are being denied, and which are being legitimized? Whom does this discourse serve?

Asking these questions and being committed to revisiting them regularly outlines the project's ethical horizon, prompting its members to continually think of ways to create spaces where knowledge can circulate dialogically, where all voices matter, and where scientific dissemination is effective precisely because the walls separating scientific knowledge from popular knowledge can be collectively redrawn.

## Final Considerations

The Polyphonies Extension Project, through transdisciplinary and dialogical practices, seeks to disseminate scientific knowledge beyond the university, thus breaking down walls and the hierarchy of knowledge. Its activities are guided by transdisciplinarity, gaining even more strength through dialogue, which aids in the development and conduct of events, making them accessible to the general public and constructing the project collaboratively. The project's actions focus on knowledge dissemination, understanding it as a process collectively gestated from the encounter of different subjects who have the opportunity to hear and be heard. In this sense, it can be said that Polyphonies' ultimate goal is to contribute to social transformation by fostering and encouraging the invention of complex, rooted, and relevant knowledge addressing the issues affecting the various actors and contexts shaping societies.

Thus, the events organized by the project reflect its interest in dialogue and contact with the other, marked in their names. "Polyphonies," "Bar Talks," and "Clubefonia" remove the rigidity with which scientific information is typically approached, giving rise to relaxed and potent conversations, precisely because they are more than "information transfer" venues. The audience is not seen as passive; on the contrary, their thoughts, cultures, and knowledge are incorporated into the dialogue to broaden the contact and understanding of reality. Therefore, it is valid to say that Polyphonies works with the plurality of voices, ideas, people, cultures, and knowledge. Driven by the possibility of viewing the world through a transdisciplinary lens, the project seeks to learn, express, and foster this vision through its actions.

However, there are challenges and room for improvement. Among the challenges, the Polyphonies team is dedicated to finding strategies to "break the bubble," that is, to increasingly mobilize the participation of people outside the university who have access to the project and its events. In this endeavor, the group is organizing to promote the project itself through various social media (Instagram, WhatsApp, Facebook, etc.), emphasizing its interest in an audience with diverse educational levels, backgrounds, and social roles.

Another challenge is imposed by the limitations of the virtual event environment. While it enables breaking physical barriers by bringing together individuals from different cities, it also restricts the intensity of possible interactions, particularly affecting the dialogue with the participating audience, which tends to be more passive in this scenario.

Aware of these and other difficulties, Polyphonies remains committed to its goal of enabling knowledge exchange and re-establishing the long-lost connection between science and society through its actions, bringing the community to a new place: that of a knowledge builder, thus contributing to scientific dissemination.
