---
author: 
  - name: Mariana Tavares Cavalcanti Liberato
    url: http://lattes.cnpq.br/3695805862483991
    orcid: 0000-0002-9410-0437
    email: marianaliberato@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Camila Ribeiro de Oliveira
    url: http://lattes.cnpq.br/9072832065292799
    orcid: 0000-0003-2975-7106
    email: camisrdeo@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Marta Clarice Nascimento Oliveira
    url: http://lattes.cnpq.br/8050372004323081
    orcid: 0000-0002-3720-1418
    email: martaclarice03@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Natália Matos de Souza
    url: http://lattes.cnpq.br/1127913530059031
    orcid: 0000-0001-5064-5761
    email: nataliamatosdesouza@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Vinicius Nogueira Lopes
    url: http://lattes.cnpq.br/6427575596872072
    orcid: 0009-0008-8651-7022
    email: vininogueira852@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará

filters:
  - section-bibliographies
bibliography: liberato_contagios.bib
reference-section-title: References
---

# Possible Contagions: Creating Spaces for an Anti-Asylum Psychology

## What Moves Thought to Think

The work we present here originates from our commitment to building a society without asylums. From a Deleuzian perspective that "more important than thought is what 'gives one to think'..." [@deleuze2003proust, p. 89], we were driven by this struggle to create devices that articulated what was experienced in contact with our field of intervention, namely a Psychosocial Care Center (CAPS), and the production and dissemination of knowledge, in an attempt to invent spaces, beyond academic activity, that enable the deconstruction of the stigma of madness.

The production of knowledge constructed in/through immersion in the field relies on the perspective of the tension that the insertion of bodies in a given territory exerts, as it drives the construction of new knowledge, practices, and experiments. Referencing cartography as a research method and access to reality, according to Barros and Kastrup [-@passos2009cartografar], the cartographer opens up to the movement of a territory and unravels variables of a production process in this contact.

In this sense, the experience of organizing an event in honor of the National Day of the Anti-Asylum Struggle emerges as a significant technical production, enabling reflection on constructing engaged and embodied knowledge that extends beyond classrooms and academic walls. Organized by the PASÁRGADA group: Promotion of Art, Health, and Guarantee of Rights, linked to the Department of Psychology and the Graduate Program in Psychology at the Federal University of Ceará (UFC), Fortaleza campus, in partnership with the substitute service, other groups, and social movements, the Anti-Asylum Week, held in 2022, constituted an event aiming to engage the community in defending care in freedom, based on the need to irradiate a new social vision affirming madness in the sphere of coexistence, with free circulation in the city's fabric.

In this venture, we started with a perspective that conceives defending the rights of people in psychological distress as a social transformation project that goes beyond the physical extinction of asylums and all societal mechanisms of exclusion and silencing of madness, understanding that "the asylum issue echoes far beyond the psychiatric hospital walls or the strict domain of asylum practices, extending throughout the social fabric" [@pradofilho2020breve, p. 55]. In other words, the production of this event stems from the idea that resisting the asylum system requires contaminating the streets, challenging the thoughts of those entrenched in oppressive and exclusionary perspectives on madness and difference.

With Deleuze [-@deleuze2003proust], we learned that "without something that forces one to think, without something that violates thought, it means nothing" (p. 89). Thus, to provoke thought beyond what is prescribed by common sense, it is necessary to create a state of strangeness, always involuntary, that breaks the mere recognition of the external world, which is provoked by signs: “what forces us to think is the sign. The sign is the object of an encounter; but it is precisely the contingency of the encounter that guarantees the necessity of what it makes us think” [@deleuze2003proust, p. 91].

Thinking is, therefore, an activity triggered involuntarily under the violence of encountering signs, which should not be confused with signifiers, as signs have no pre-given meaning to be recognized. Instead, "the sign implies in itself heterogeneity as a relation" [@deleuze2003proust, p. 21], so every sign implies an opening of worlds that affects us in such a way as to push our faculties beyond their usual limits. Thus, the sign is directly affective, and thinking originates from affection. This is particularly important to us as it provides the necessary openness to conceive the production of knowledge as an intensive and bodily experience, far from a recognitive attitude.

What we advocate here is that thinking does not start from something pre-established but from production through sensitivities. Our challenge, therefore, was to enable intensive encounters through signs that affirmed the production and propagation of knowledge as a sensitive and engaged experience. More than that, we know that the sign, as an affect, is effective in constructing other worlds incompatible with the established [@nascimento2012teoria], so the centrality of our initiative was linked to creating disturbance spaces that, by force of the encounter, tensioned the place of madness in the social body and infected others with the idea of care in freedom.

Thus, we proposed an event that constitutes a technical production aimed at constructing an anti-asylum psychology. This initiative is especially necessary during setbacks in Brazil's national mental health policy, resulting from the approval of a series of political projects contrary to the ideals of a society free from asylums, whether mental or structural. Given this scenario, we argue that it is more necessary than ever to provoke thought about madness and mental health care, preparing the ground for creating other ways of relating to difference.

We also remember that the persistence of an asylum logic within the substitute services is one of the major challenges faced by the Psychosocial Care Network (RAPS), often originating in the formative processes of health professionals who fail to deconstruct the relations of domination and chronification of users typical of asylum models. To resist this, we created an innovative product, resulting from our interventions and studies on mental health care, which places the affection and contagion of reality as premises for producing and disseminating knowledge in times of tension and dispute in this field. Below, we will share some of the construction of this event, which was, above all, an experiment in knowledge produced with the other.

## Affecting and Moving: Inventing the “Anti-Asylum Struggle Week”

The Anti-Asylum Struggle Week initiative results from studies on mental health care and the continued insertion that the PASÁRGADA program has had in this field since 2019. Through university extension, the group has developed activities in two Psychosocial Care Centers (CAPS) - Type II in Fortaleza-CE. These actions include therapeutic group follow-ups, activities in the services' waiting rooms, and actions beyond these facilities' walls.

Such interventions rely on art as a device that enables fluidity of expression in its various forms and expands communicative notions by transcending language through senses that pulse beyond speech. Deleuze and Guattari [-@deleuze2010filosofia] affirm that “art wants to create a finite that restores the infinite: it traces a composition plan that carries, in turn, monuments or composed sensations, under the action of aesthetic figures” (p. 253). In this sense, the inventiveness characteristic of this device allows access to a given content that transcends the artist, the work, and the subject who visualizes it, dimensioning a vibrant reality proposing new ways of accessing life aesthetically and sensitively.

With this perspective, we understand that art is not limited to a humanizing tool for care, as it is also a resource that offers, through experimentation, new subjective anchors for people in psychological distress, giving them the possibility to reinvent themselves and the world. As Costa, Zanella, and Fonseca [-@costa2016psicologia] point out, art influences the composition of overflows of the established limits imposed on research, intervention, and existence. Thus, it arises for us as a form of resistance to the hegemonic ways of living imposed on madness, affirming a process of expanding the fields it can inhabit, whether concrete – in this case, social – or subjective. Therefore, our alliance with art is also made from an ethical and political struggle perspective, linked to overcoming psychiatric and asylum institutions, which have gained strength in recent years.

Due to the social isolation situation triggered by the COVID-19 pandemic in 2020, care provided in CAPS was mainly limited to psychiatric and psychological care and medication distribution, given the impossibility of conducting collective activities such as therapeutic and operative groups in person. Consequently, a scenario favorable to advancing outpatient and medicalizing care logic was cultivated in Fortaleza's psychosocial care network before the pandemic crisis [@guimaraes2016inovacao], but which severely worsened during this context, implying a significant setback for psychiatric reform and the anti-asylum project, already greatly weakened by the advance of neoliberalism and conservatism in the country.

The vision of constructing the Anti-Asylum Struggle Week event arose from the loosening of sanitary measures and the return of in-person activities in early 2022. It also emerges from the memory that constitutes PASÁRGADA, which, in its years of existence, has conducted various actions stitching together health services, universities, social movements, and society. Crossed by what Deleuze [-@deleuze1992conversas] asserts when he says “a little bit of possible, otherwise I suffocate...” (p. 131), we are called to re-enchant May 18 in a context of psychological, social, and political fragility, as well as setbacks in psychiatric reform and uncertainty regarding the reality we once knew and are called to inhabit again after the COVID-19 calamity.

It is worth noting that the National Anti-Asylum Struggle Day reflects a series of disputes and the active participation of the community, workers, families, and people in psychological distress. Espírito Santo, Araújo, and Amarante (2016) state that, from the emergence of the Mental Health Workers Movement (MTSM) in the 1970s, denunciations against the treatment model then used as a reference in the mental health field reverberated. The strictly biomedical perspective, along with reports of violence against the bodies inhabiting so-called care spaces, described an unsustainable situation, resulting in the 8th National Health Conference and, a year later, the First National Mental Health Conference. The emergency and change scenario produced during the second MTSM congress in 1987 established May 18 as a symbolic date for maintaining and engaging in a rights struggle, care in freedom, and de-asyluming life.

Amarante and Nunes [-@amarante2018reforma] highlight that during the occasion, the slogan “For a society without asylums” was created, and the social movement became more complex, gaining participation from new social actors (users, families, and other human rights activists). Additionally, a new horizon of demand was built, focused on deconstructing the asylum logic and its institutional apparatus, thus constituting itself as the “Anti-Asylum Struggle Movement (MLA).” According to the authors:

> A decisive element for this expansion \[of the MLA\] was the creation of the National Anti-Asylum Struggle Day in Bauru. May 18 would serve to awaken critical thinking in society about the institutional violence of psychiatry and the exclusion of people in psychological distress. It can be considered that the objective was successful to the extent that, since then, political, scientific, cultural, and social activities have been carried out not only on the day in question but throughout the month of May, which came to be considered the Anti-Asylum Struggle Month. Given the significant repercussion of the events organized by the MLA and their substantial participation in broader health issues, the term “mentalistas” (in reference to heavy metal) became widely used to characterize the “noise” caused by this social actor [@amarante2018reforma, p. 2070].

Thus, given the importance of this date, guided by the construction of comprehensive care, in freedom and integration (in the network), we questioned how to create crossings that could disrupt what is rigid in psychosocial care and continue the proposal of care that transcends the service structure. The challenges arise from the intersection of a moment of collective mourning, physical reinsertion into previously uninhabited spaces, and significant sensitization regarding mental health and social ties. Therefore, we are called to challenge the established and bet on inventiveness and affection as mobilizing forces, creating the 2022 Anti-Asylum Struggle Week event.

This event featured diverse activities distributed over five days, namely:

1.  Monday: a procession through Benfica and a discussion circle at the university.
2.  Tuesday: an action in the waiting room at CAPS II - CORES IV and a panel discussion at the university.
3.  Wednesday: participation in the public act promoted by the Ceará Anti-Asylum Struggle Forum (FCLA) in the city center.
4.  Thursday: organization of an exhibition; and
5.  Friday: in-person display of the “Desambula: so that desire can flow” exhibition at São José Theater.

The construction and implementation of this venture were only possible thanks to the alliances built with partner institutions and professionals, users, social movements, university sectors, and a range of agencies that, according to Deleuze and Guattari [-@deleuze2003kafka], “... extend or penetrate an unlimited field of immanence that melts segments, freeing desire from all its concretions and abstractions, or at least actively struggles against them to dissolve them” (p. 145). Thus, we sought to create crossings that brought movement to the crystallized practices in the mental health field.

The event began on May 16, Monday, with a procession through the streets of Benfica, a neighborhood with a high flow of people and the location of the UFC Psychology Department. The act was carried out alongside the carnival block “Doido é Tu!”. This moment aimed to compose a struggle that arises from alliances and through boundary transgression, proposing a contagion with the city, the university, art, and culture, weaving the struggle for ethical-political care. As Martins [-@martins2009ode] points out, “in anti-asylum practices, the city, madness, and art meet and together make an appeal for life. They demand less life to be lived and more pulsating life...” (p. 86).

The procession emitted notes that vibrated through the city, prompting passing cars to honk and pedestrians to shout with us, through a porosity that permeated boundaries. We took flight, sang, walked, danced, shouted, and landed. The act ended at the Moreira Campos Forest, located in the Center for Humanities I at UFC, where we gathered and settled for a discussion circle titled “Anti-Asylum Struggles: Still!”. This location was purposely chosen, as it has a high flow of people moving daily, potentially engaging with the proposed discussion.

We aimed to enter the university by shattering crystallizations regarding madness and seeking to broaden this debate not only within a course focused on mental health, such as Psychology, but for society as a whole. In agreement with the Basaglian perspective, we proposed to discuss the possibility of inventing new strategies for restructuring cultural organization regarding the presence of the subject in distress and the disturbance they determine, producing other modes of expressing this experience of suffering [@basaglia2010escritos].

Settling visibly to passersby, singing, dancing, dialoguing, and inquiring: can madness occupy the university? In this composition between passing flows, the large circle included users and service professionals, professors, and students from various university courses. It was realized through the collective space of sharing and discussing the history of the Anti-Asylum Struggle and Brazilian Psychiatric Reform, its processes and setbacks, and the need to maintain it today.

At this moment, the struggle was tensioned as pluralized, as it is also an anti-racist, anti-LGBTQUIAP+phobic, and anti-fascist struggle, configuring itself as a demand for care that promotes quality of life for the bodies occupying this space. Basaglia [-@basaglia1985instituição], analyzing the condition of the institutionalized, places the subject in psychological distress as a subject without rights, subjected to institutional powers, socially excluded due to their social and economic condition rather than the illness itself. Stela do Patrocínio [-@patrocínio2009reino], a Black poet interned for almost 30 years, tells us that “being interned is being imprisoned all day” (p. 47), thus the asylum being a strategy for controlling and imprisoning bodies, mainly Black and poor. Therefore, it is crucial to think of mental health care that is provided in freedom and intersectionalized, recognizing the identity markers placed in the field of subordination, producing illnesses and new forms of the asylum.

On the second day of the event, we organized a morning action in the waiting room at CAPS II - CORES IV. This activity is a standard practice of Pasárgada since its insertion in health facilities, during waiting times for appointments or medication, for example. We propose interactive activities, provocative installations, and interventions that move the bodies present, aiming to subvert the outpatient logic marking this waiting time. Furthermore, aligning with Deleuze’s [-@deleuze1999ato] association between art and resistance, we aim to construct other possibilities for life production through the contact between the device and mental health.

Understanding the possibility of constructing possible paths of life, other creations for existence, the activity had the key question "What do we do to be free?", with pens, colored pencils, markers, glue, colorful glue, and images, as well as a poster on an easel for producing a collective work from this trigger. The objective was to think about what freedom meant to each person, what affected them in this sense, and how it could be understood expansively and collectively, understanding the processes of subjectivation and the ways existence weaves itself beyond the neoliberal and individualistic ideal. The action was planned as care involved in not individualizing users, proposing, instead, a process of constructing collective resistances against systematic oppressions that attempt to suffocate difference, through forming alliances as a possible bet in the care in freedom experimentation process.

Additionally, in the afternoon, a panel discussion was held at the Center for Humanities II at UFC, proposed by VIESES (Research and Interventions on Violence, Social Exclusion, and Subjectivation Group), in partnership with FCLA, with support from PASÁRGADA, titled “Mental Health Care in Ceará: Concerns and Propositions.” The panel discussion focused on the mental health of children and adolescents and their current challenges; necropolitics and its impacts on mental health; and political disputes surrounding care for alcohol and other drug users. We understood this space as an opportunity to provoke critical academic thought about the reality of mental health in Ceará today, articulating different social actors from various contexts.

The setbacks in mental health policies highlighted by Passarinho [-@passarinho2022retrocessos] when discussing government funding of therapeutic communities and psychiatric hospitals in the Psychosocial Care Network (RAPS) emerged in this moment through the voices of workers and users. Moreover, the poor management of worker care, alongside the scarcity of public contests in this field – strategies for strengthening the bond between professionals and users through the permanence in the service – was highlighted as a central tool for proposing ethical care.

The disregard for children and adolescents' mental health due to lack of incentive and the policy of youth mortification marked by race, gender, and socioeconomic status was another emphasized topic. The logic of making live and letting die that promotes life only for bodies considered normal was evident at this moment through the reports brought by those involved in this network, corroborating Mbembe's [-@mbembe2018necropolitica] notion that, “in the economy of biopower, the function of racism is to regulate the distribution of death and make possible the murderous functions of the State” (p. 18).

Furthermore, it was stated that the lack of incentive for harm reduction policy in favor of prohibitionist logics perpetuating the dynamics in the field of assistance to alcohol and other drug users chronifies the problem and reproduces asylum and violence practices. Harm reduction promotes a joint construction for experiences with psychoactive substances involving participation in policy management in the field and the reduction or even cessation of drug use [@passos2011redução]. The panel discussion discussing these three axes raised many concerns and brought propositions around what was discussed, aiming to take the highlighted points to conferences and forums, contributing to public policy planning.

On the third day of action promotion, May 18, 2022, we made an ethical-political commitment to be in the street, participating in the act organized and led by FCLA and mobilizing the academic community to join this activity. The concentration for the political demonstration for care in freedom took place at Praça do Ferreira, in the city center, to create new visibility zones for madness, as Silva [-@silva2006espacos] points out, the place is historically marked by

> ... significant social content, constituting itself, over the years, as an “icon” for Fortaleza. A traditional meeting and sociability place, it was an excellent leisure space, still today the square of greatest representation in the center. The great vitality that takes place there becomes noticeable through cultural events, social manifestations, and the persistence of some uses that have been resisting the transformations in that public space. (p. 106)

Amarante [-@amarante2007saude] states that there is a sociocultural dimension in the Brazilian psychiatric reform process that is strategic in attempting to provoke the social imaginary through questioning about madness, mental illness, and psychiatric hospitals, based on the cultural and artistic production of social actors composing this movement. In this sense, historically, as mentioned above, May 18 and the following days mark social, cultural, and political movements with the participation of users, professionals, and families to claim and guarantee rights, care policies, and occupy the city for the anti-asylum struggle.

Thus, being on the street, occupying the city with art, music, dance, and slogans, is necessary. Inhabiting this territory as a meeting point, with bodies denied access to public space, is a process of affirming difference. Being there, professionals, users, families, students, politicians, and militants, is a bet on destabilizing what is set in macro-politics and the asylum structure, announcing our presence as a demand for the right to the city. Additionally, persisting as a group gathering on this date, amid a challenging political scenario – especially concerning public health – constitutes a collective construction of care and an ethical-political commitment to the anti-asylum agenda that must be strengthened. We also emphasize that participating in this act highlights the perspective of knowledge not only produced within university walls theoretically but also constructed through experimentation with the social actors involved and their life contexts.

Again, the carnival block “Doido é tu!” was present, enhancing this moment with music and dances. We produced posters, raised flags, and walked together to the headquarters of the Fortaleza Municipal Health Secretariat, where a letter written by FCLA listing and demanding points for effective care in Fortaleza's psychosocial care network was delivered.

On May 19, we focused on organizing and assembling our final action for that Week, which was characterized by the in-person exhibition of the “Desambula: so that desire can flow” project. Thus, on May 20, we had this exhibition in partnership with CAPS II - CORES IV in Fortaleza. The idea for this action emerged from the desire to echo this artistic presentation, which initially took place virtually, with production starting in 2021, when the idea was proposed to one of the art therapy groups to create and organize works for an exhibition, culminating in 2022. The objective was to think and create an exhibition together with the artist and the group users, constructing a collective exhibition from the activities proposed in the group, resulting in the arts, the theme of the exhibition, the website, and the curatorial process.

Despite the difficulties of constructing a care process through hybrid contact amid a pandemic, the virtual exhibition opened on February 16, 2022, with the website's launch alongside the artists in a discussion circle via Google Meet, and closed on March 16, 2022. Thus, primarily proposing a relationship transforming Western society's relationship with madness (Amarante, 1994), we brought the exhibition to the in-person format at São José Theater in Fortaleza, concluding the Anti-Asylum Struggle Week.

São José Theater, the chosen exhibition site, was created in 1914 and is a historic facility in Fortaleza, located in the city center, representing a significant cultural hub. Recently renovated after years of closure, it now features an important cultural program for the city. Thus, the choice of the theater stemmed from our previously stated desire to occupy the urban space in highly trafficked locations.

The works composing the in-person exhibition were the same as those in the virtual exhibition but with a different configuration, featuring interactive frames made by the artist-users with materials like bottle caps, sequins, threads, glitter, and even seeds. Additionally, all works were suspended with colorful strings, proposing movement with bodies beyond manual touch with the materialities. The room was arranged so visitors could follow a path starting with reception and information about the exhibition's construction and leading to an installation with two projectors: one displaying audiovisual works and the other showing strictly visual works, all produced in the group space.

There were also some artistic installations proposing reflections on themes intersecting the mental health field. A mirror installation with the famous phrase “up close, nobody is normal,” from Caetano Veloso's song “Vaca Profana,” invited people to interact and photograph themselves. Another installation, “How to Become Uncompressed? II,” by Caio Prado, in a corner, invited people to interact by discarding empty medication blister packs, prompting reflections on the medicalization of life. Finally, we organized a collective creation space where visitors could overflow the affections of this encounter. We placed poster boards on an easel before the room exit, providing paint, colored pens, threads, and glue for composing a materiality consisting of writings, drawings, and interventions by passersby after the visit.

Throughout the day, over 100 people visited the exhibition, including the artists and their families, users from other CAPS in Fortaleza, such as those from CAPS AD in Regional IV, health professionals, public university students, private college students, high school institutions, technical courses, and many curious individuals. The purpose was to give visibility to the artists and their works, as there was a desire in the group to exhibit, and many had never had the opportunity, while also considering how art holds an essential place of possibility when it comes to mental health care and the de-stigmatization of these individuals, positioning the city as a point of involvement.

Cities, beyond buildings, houses, and intertwined streets producing materiality, are also stages for affections and social relations (Mansano, 2016). By understanding the city as this place of intertwining, we also understand that it is where life, encounters, and discussions are produced. Madness, long imprisoned – from the 17th century, as Foucault [-@foucault1975doença] mentions, saying that madness entered this world of exclusion by an ideal of incapacity and reconstruction of the social space of the time – must also be intertwined in this city. Going out into the world implies, therefore, a form of resistance to these historical policies of exclusion, violence, and stigmatization of these bodies.

## Final Considerations

Passos et al. [-@passos2021remanicomialização] point out that the country is advancing towards a process of (re)asylumization driven by the interest of actors representing a conservative and neoliberal political project centered on maintaining privileges and focused on privatizations and the revival of social control practices. Therefore, we observe the importance of events like the one proposed for producing materiality seen, touched, and felt, as well as for producing sensitization, reflection, and debates on the anti-asylum agenda, acting on the de-stigmatization of madness and proposing care produced in freedom.

A Psychology that aims to be Anti-Asylum must seek, within the University, to produce knowledge articulated with the proposition of new ethical and political horizons, seeking to combat this scenario of oppression and stigma. It must, therefore, commit to fostering solutions beyond academic walls, enabling exchanges with subjects and groups often marginalized from these discussions but affected by them and creating resistances in their daily lives.

In this sense, we emphasize that promoting an event like this, aimed at creating displacements in the very form of producing knowledge and academic practices, was only possible from a perspective of collective work and with the different social actors forming this context. Mutual contagion of experiences, thoughts, and creations. A technical production, but also alive, launching us into new problems and concerns for our studies, research, and practices. At the interface between the University and society, we affirm an affective engagement centered on breaking rigid models of knowledge production, forming ourselves also as body-researcher-experimenters of an anti-asylum mental health and new ways of learning, caring, and living.
