# About the Authors

**Adrielle Jennifer Candido Coelho**

Psychology student at the Federal University of Ceará, Sobral campus, and volunteer extensionist for the Subjectivation and Sexuality Studies and Extension Project (SuSeX).

**Aldemar Ferreira da Costa**

Graduate, Master, and Ph.D. candidate in Psychology at the Federal University of Ceará. Member of the Research and Interventions Group on Violence, Social Exclusion, and Subjectivation (VIESES).

**Alex Sandro de Moura Grangeiro**

Clinical Cognitive-Behavioral Psychologist (CRP 11/07194), graduated from the Federal University of Ceará (2011), with training in neuropsychology from the University of São Paulo (2020), a master's degree in Psychology from the Federal University of Ceará (2014), and a Ph.D. in Social Psychology from the Federal University of Paraíba (2017). Currently, Adjunct Professor I at the Federal University of Ceará (UFC - Sobral campus), full member of the Research Ethics Committee of the Santa Casa de Misericórdia de Sobral, and Coordinator of the Neurocognitive and Behavioral Assessment Research Center (Neurocog - UFC).

**Ana Cecília Carenina Machado Mourão**

Graduate in Dentistry at the Federal University of Ceará, Sobral campus. She was a volunteer fellow of the Scientific Initiation Program (PIBIC) in the area of Dental Radiology and an Extension Project fellow in the same area. She also participated in the Polifonias Project of the Psychology course.

**Ana Kesia Silva Faustino**

Psychology undergraduate at the Federal University of Ceará, Sobral campus. PIBIC scholarship holder (ICT-FUNCAP). Extensionist for the Polifonias Project and the Água de Chocalho Project, affiliated with the Laboratory of Clinic, Subject, and Public Policies (CLIPSUS). Intern at the Rehabilitation Center of Sobral-CE.

**Ana Laís Carvalho de Sousa**

Master’s student in Psychology and Public Policies at the Federal University of Ceará, Sobral campus. Psychology undergraduate at the Estácio University Center of Ceará, Via Corpvs campus. Bachelor in Administration from the State University Vale do Acaraú.

**Andie de Castro Lima**

Bachelor in Psychology from the Federal University of Ceará (UFC). Specialist in Human Rights, Social Responsibility, and Global Citizenship from the Pontifical Catholic University of Rio Grande do Sul. Master and Ph.D. candidate in Psychology from the Graduate Program in Psychology at UFC. Member of the Environmental Psychology Research Laboratory (Locus) at UFC.

**Andressa da Silva Rodrigues**

Psychology undergraduate at the Federal University of Ceará, Sobral campus.

**Antonio Anderson Mota da Silva**

Master in Psychology and Public Policies from the Federal University of Ceará (UFC). Specialist in Special Education from UNINASSAU. Psychology graduate from UFC. Works as an Educational Advisor in the Sobral City Hall. Dedicated to studying topics in Educational Psychology, Educational Guidance, Social Psychology, Clinical Psychology, and higher education teaching.

**Ariadsa Mesquita Aragão**

Psychology undergraduate at the Federal University of Ceará, Sobral campus. Extension scholarship holder for SuSex.

**Antonia Renata Lopes Lima**

Psychologist (Centro Universitário Católica de Quixadá, 2017). Postgraduate in ABA intervention for autism and intellectual disability (CBI of Miami). Master in Psychology and Public Policies (Federal University of Ceará, Sobral campus, 2023). Permanent public servant in the municipality of Banabuiú.

**Bárbara Éllen Viana Sales**

Psychology graduate from the Federal University of Ceará, previously a scholarship holder at the Laboratory of Studies on Inequalities and Diversities. Currently works in Clinical Psychology with a psychoanalytic approach.

**Beatriz Alves Viana**

Ph.D. in Psychology from the Federal University of Ceará (UFC). Master in Psychoanalytic Theory from the Federal University of Rio de Janeiro. Specialist in Mental Health. Psychologist from UFC. Professor and internship manager at Uninta University Center.

**Brígida Sousa de Oliveira**

Psychology undergraduate at the Federal University of Ceará, Sobral campus. Since 2022, a volunteer scholarship holder at SuSex and the Laboratory of Studies on Inequalities and Diversities (LAEDDES). Previously interned at Cras Regina Justa, located in Sobral-CE.

**Camila Ribeiro de Oliveira**

Graduate and master’s student in Psychology at the Federal University of Ceará. Member of PASÁRGADA: Promotion of Art, Health, and Rights Assurance. CAPES scholarship holder.

**Camilla Araújo Lopes Vieira**

Professor of the Psychology undergraduate program and the Master’s in Psychology and Public Policies at the Federal University of Ceará, Sobral campus. Postdoctoral in Psychoanalysis at the State University of Rio de Janeiro.

**Carla Cecília Mendes Oliveira**

Psychology student at the Federal University of Ceará, Sobral campus, and extensionist for SuSex.

**Carla Jéssica de Araújo Gomes**

Psychology graduate from the Federal University of Ceará (UFC). Master’s student in Psychology at UFC. CAPES scholarship holder. Member of VIESES.

**Carla Renata Braga de Souza**

Psychoanalyst, Psychology graduate (State University of Paraíba), Ph.D. and Master in Psychology from the University of Fortaleza (UNIFOR). Currently, a postdoctoral fellow in the Department of Psychology at the Federal University of Ceará and extensionist for the “Clinic, Aesthetics, and Politics of Care” Extension Program (CEPC) affiliated with UFC. Associate member of CLIO - Psychoanalysis Association. Lecturer at Christus University Center.

**Carolina Silveira Leitão Melo**

Psychology graduate from the Federal University of Ceará (UFC), Sobral campus. MBA in People Management from UNIFOR. Master’s student in Psychology and Public Policies at UFC, Sobral campus, and currently specializing in Analytical Behavioral Therapy at Núcleo Tríplice. Previously worked as an organizational psychologist at SINE-IDT, Grendene, and Coca-Cola. Currently works as a clinical psychologist.

**Cícera Mônica da Silva Sousa Martins**

Ph.D. candidate in Psychology at the Federal University of Ceará (UFC). Holds a degree in Psychology from Leão Sampaio College (2014), a specialization in Public Health Policies from the Regional University of Cariri (2016), and a Master’s in Psychology from UFC (2020). Affiliated with two research centers: the Interdisciplinary Laboratory of Social Management Studies (LIEGS-UFCA) and the Environmental Psychology Laboratory (LOCUS-UFC).

**Cristiane Ferreira de Souza**

Psychology graduate from the Federal University of Ceará. During her undergraduate studies, she held a technology transfer scholarship from the Ceará State Foundation for Scientific and Technological Development Support (FUNCAP).

**Dária Maria Barbosa Dedê**

Psychologist (Centro Universitário Católica de Quixadá, 2018). Postgraduate in Neuropsychology (Faculdade Única de Ipatinga, 2020) and Clinical Psychology, focusing on Existential, Humanistic, and Phenomenological Psychology (Faculdade Venda Nova do Imigrante, 2020). Master’s student in Psychology and Public Policies at the Federal University of Ceará, Sobral campus. Permanent public servant in the municipality of Groaíras.

**David Sousa Rodrigues**

Psychology graduate from the Federal University of Ceará, Sobral campus.

**Davi Lucas Moraes**

Medical student at the Federal University of Ceará. Former member of VIESES.

**Deni Elliot Noronha Lopes**

Master in Psychology and Public Policies from the Federal University of Ceará, Sobral campus (2021), Psychology graduate (2019) from the same university. Works as an Educational Advisor in Sobral. Member of PESQUISAMUS (Research Group in Education, Arts, and Music). Conducts research in education, youth, arts, and public policies.

**Elcides Hellen Ferreira Landim Barreto**

Psychologist, Ph.D. candidate, and Master in Psychology from the Federal University of Ceará - UFC, specialist in Psychology Applied to Education from the Regional University of Cariri - URCA.

**Eliandra Estevam Abreu**

Psychology undergraduate at the Federal University of Ceará. Member of VIESES and extensionist for the Maquinarias Project: childhoods in invention.

**Emanuel Meireles Vieira**

Professor in the Department of Psychology and the Graduate Program in Psychology at the Federal University of Ceará. Member of VIESES. Ph.D. in Psychology from the Federal University of Minas Gerais.

**Érica Atem Gonçalves de Araújo Costa**

Ph.D. in Brazilian Education from the Federal University of Ceará (UFC). Professor in the Psychology course at UFC in Fortaleza. Faculty member of the Professional Graduate Program in Psychology and Public Policies at the Federal University of Ceará, Sobral campus. Member of VIESES, where she coordinates the extension project Maquinarias: childhoods in invention. Tutor for the Tutorial Education Program - Pet - Psychology.

**Esthela Sá Cunha**

Graduate and Master in Psychology and Public Policies from the Federal University of Ceará, Sobral campus. Professor at the INTA University Center and the 05 de Julho College of Sobral.

**Fábio Pinheiro Pacheco**

Psychology graduate from the State University of Ceará (UECE), Master and Ph.D. in Psychology from the Federal University of Ceará. Adjunct Professor in the Psychology course at UECE. Member of the Environmental Psychology Research Laboratory (Locus).

**Francisca Denise Silva Vasconcelos** (*in memoriam*)

Ph.D. (2011) and Master (2004) in Sociology from the Federal University of Ceará. Graduate (2000) in Social Sciences from the same institution.

**Francisca Valéria de Sousa**

Psychologist graduated from the Federal University of Ceará and Master in Psychology and Public Policies from the same institution. Member of the Laboratory of Practices and Research in Psychology and Education (LAPPSIE).

**Francisco Bruno Paz Soares**

Psychology graduate from the State University of Piauí (UFPI - 2017) and Master (2018) in Psychology from the same institution.

**Francisco Pablo Huascar Aragão Pinheiro**

Psychologist, Master in Psychology, and Ph.D. in Education, all degrees obtained from the Federal University of Ceará. Professor in the Psychology undergraduate program and the Professional Graduate Program in Psychology and Public Policies at the Federal University of Ceará, Sobral campus. Research productivity fellow at the Ceará Foundation for Scientific and Technological Development Support.

**Gabriele Sousa Costa**

Psychology graduate from the Federal University of Ceará, Sobral campus. Member of the Laboratory of Practices and Research in Psychology and Education (LAPPSIE). Participates in the extension project Elaborar: understanding and transforming work.

**Giovana Freitas Oliveira**

Psychology undergraduate at the Federal University of Ceará. Research assistant at the Laboratory of Studies and Research in Social Economy.

**Giovana Mayra Liberato de Lima**

Psychology undergraduate at the Federal University of Ceará, Sobral campus. FUNCAP scholarship holder for the project “Repercussions of External Evaluations on the Health of Ceará Teachers: Qualitative Analysis and Multilevel Mediation Model.” Extensionist for Elaborar, a project affiliated with the Laboratory of Practices and Research in Psychology and Education (LAPPSIE).

**Graciella Faico Ferreira**

Trained in Psychology, with a bachelor’s and licentiate degree from the Federal University of Rio de Janeiro (UFRJ). Specialization in Public Policies and Government Management from the Federal University of Fluminense (UFF). Master, Ph.D., and postdoctoral (ongoing) in the Graduate Program in Psychosociology of Communities and Social Ecology (EICOS/UFRJ). Researcher at GAPIS/UFRJ and Locus/UFC.

**Gracymara Mesquita Severiano**

Professor and researcher. Master in Psychology and Public Policies from the Federal University of Ceará, where she served as area coordinator in PIBID-Diversity and researcher in the Angaturama Eté project, a partnership with the University of Calgary/Canada. Works as a higher education professor. Instructor in Management and Business courses for PRONATEC/SENAC. History and Human Formation teacher in the public school system of Sobral. Holds degrees in Administration and History, with specialization in people management.

**Halaine Cristina Pessoa Bento**

Psychologist from the Federal University of Roraima (UFRR), Specialist in Human Rights, Social Responsibility, and Global Citizenship from the Pontifical Catholic University of Rio Grande do Sul (PUCRS), and Master from the Graduate Program in Psychology at the Federal University of Ceará (UFC).

**Hiara da Silva Santos Barbosa**

Psychologist from the Federal University of Piauí (UFPI), Master in Psychology and Public Policies from the Federal University of Ceará, and Specialist in Neuropsychology from Unichristus. Works as an Educational Advisor in the Municipal Education Network of Sobral-CE and as a clinical psychologist.

**Ingrid Rabelo Freitas**

Graduated in Social Work. Since 2018, serves as Advisor at the Herbert de Souza Life Defense Center, accompanying the Youth Peace Agents Group. Has experience in the field of Social Work, mainly working on the following topics: youth, peace culture, and human rights.

**Iratan Bezerra de Sabóia**

Holds a degree in Psychology from the University of Fortaleza (2002), specialization from the State University Vale do Acaraú (2006), Master (2007) and Ph.D. (2019) in Psychology from the Federal University of Ceará (UFC). Professor in the undergraduate Psychology course and the Professional Master’s in Psychology and Public Policies at UFC, Sobral campus.

**João Paulo Pereira Barros**

Professor in the Department of Psychology and the Graduate Program in Psychology at the Federal University of Ceará. Coordinator of VIESES. CNPq Level 2 Productivity Scholarship holder.

**João Paulo Sales Macedo**

Associate Professor 2 at the Federal University of Delta do Parnaíba. Holds a degree in Psychology from Santo Agostinho College (2004), Master (2007) and Ph.D. (2011) in Psychology from UFRN. Affiliated with the Graduate Programs in Psychology at the Federal University of Delta do Parnaíba (UFDPar) and the Federal University of Ceará (UFC). CNPq Research Productivity Fellow.

**Jorge Samuel de Sousa Teixeira**

Psychologist from the Federal University of Ceará (Sobral campus). Postgraduate in Hospital Psychology and Mental Health. Postgraduate in Oncology in residency (ESP/CE).

**Jose Edberto Gadelha Rocha Junior**

Psychology graduate from the Federal University of Ceará (2022). Specialist in Behavioral Analysis (2023). Works as a clinical psychologist with an emphasis on analytical-behavioral therapy and contextual behavioral therapies.

**Julia Mesquita Lopes**

Graduate in Portuguese and English Language and Literature from the State University Vale do Acaraú (UVA), Psychology graduate from the Federal University of Ceará, and Specialist in Portuguese Language and Literature (UVA).

**Juliana Maria do Nascimento Mota**

Psychology graduate from the Federal University of Ceará - Sobral campus. Master’s student in the Professional Graduate Program in Psychology and Public Policies - UFC/Sobral, in the research line: Education and Public Policies. Specialist in Educational Psychology from Quixeramobim College - UNIQ. Specialist in Gender, Diversity, and Human Rights from the University of International Integration of Afro-Brazilian Lusophony - UNILAB. Interested in the areas: Social Psychology, Psychoanalysis, Education, and topics on poverty, social gender inequalities.

**Juliana Vieira Sampaio**

Professor in the Psychology undergraduate course at the Federal University of Minas Gerais. Professor in the Professional Graduate Program in Psychology and Public Policies at the Federal University of Ceará (UFC), Sobral campus. Postdoctoral in Psychology (2020) at UFC, Ph.D. in Psychology from the Federal University of Pernambuco (2016).

**Kallyne Rose da Silva Rodrigues**

Psychology undergraduate at the Federal University of Ceará, Sobral campus. FUNCAP scholarship holder for the project “Repercussions of External Evaluations on the Health of Ceará Teachers: Qualitative Analysis and Multilevel Mediation Model.” Extensionist for Elaborar, a project affiliated with the Laboratory of Practices and Research in Psychology and Education (LAPPSIE).

**Karla Patrícia Holanda Martins**

Associate Professor in the Department of Psychology at the Federal University of Ceará (Undergraduate and Graduate). Postdoctoral in Psychology (USP). Ph.D. in Psychoanalytic Theory (UFRJ) and Master in Clinical Psychology (Puc-RJ). CNPq Productivity Fellow. Coordinator of the Extension Program (CEPC).

**Laisa Forte Cavalcante**

Psychologist (CRP-11/12879). Master and Ph.D. candidate in Psychology from the Federal University of Ceará. FUNCAP scholarship holder. Member of VIESES. Member of the female clowning collective: Cio das 5.

**Lara Thayse de Lima Gonçalves**

Psychologist (CRP-11/17144). Master’s student in Psychology at the Federal University of Ceará. FUNCAP scholarship holder. Member of the Laboratory of Psychology, Society, and Subjectivity (LAPSUS/Universidade Federal do Ceará) and the Insurgent Arts Collective: Colectivizing Resistances.

**Larissa Ferreira Nunes**

Psychology graduate. Ph.D. candidate and Master in Psychology from the Federal University of Ceará. CAPES scholarship holder. Specialist in Mental Health from the State University of Ceará. Member of VIESES.

**Laryssa Ferreira Rabelo**

Psychology student at the Federal University of Ceará. Member of the Maquinarias extension project: childhoods in invention, affiliated with VIESES.

**Lívia Lima Gurgel**

Psychology graduate from the Federal University of Ceará (UFC). Master in Social Psychology from the Graduate Program in Social Psychology at the State University of Rio de Janeiro. Member of VIESES. Ph.D. candidate in the Graduate Program in Psychology at UFC and psychologist in the Primary Care of SUS.

**Luana Paiva da Silva**

Psychologist graduated from the Federal University of Ceará. Former member of the Laboratory of Studies on Inequalities & Diversities (LAEDDES). Specialization in Mental Health and ongoing in School and Educational Psychology from FAVENI. Works as a psychologist in the Municipal Education Department of Meruoca-CE. CRP-11/18714.

**Lucas Araújo da Silva**

Psychology undergraduate at the Federal University of Ceará, PET Program scholarship holder affiliated with the Department of Psychology (Federal University of Ceará) and member of Pasárgada.

**Lucia Maria Bertini**

Psychology graduate (PUC/RS), Specialist in Strategic Management of Public Policies (UNICAMP), and Master in Planning and Public Policies (UECE). Ph.D. candidate in Psychology (Federal University of Ceará) and researcher at VIESES. Professionally works in public policies, security policies, and human rights.

**Luciana Fontenele de Sena**

Psychology graduate from the Federal University of Ceará.

**Luciana Lobo Miranda**

Full Professor in the Department of Psychology at the Federal University of Ceará and the Graduate Program in Psychology at the same institution. Coordinator of LAPSUS and the Insurgent Arts Collective: Colectivizing Resistances.

**Luiza Barbara Cunha Freire**

Psychology undergraduate at the Federal University of Ceará (Sobral campus). PIBIC scholarship holder for the project "Research-intervention: sexual and reproductive rights in social assistance.” Extensionist for SuSex.

**Luiza Silva de Lima**

Psychology undergraduate at the Federal University of Ceará - Sobral campus. PET Program scholarship holder (Federal University of Ceará). Extensionist for PASF (Learning About Children Project) and the GESTUS MENTIS League (Interdisciplinary Mental Health Study Group of Sobral).

**Maria Lídia de Farias Araújo**

Psychology graduate (Federal University of Ceará), Postgraduate in Organizational and Work Psychology. Clinical psychologist and organizational psychology consultant.

**Mariana Tavares Cavalcanti Liberato**

Psychology graduate from the Federal University of Ceará (UFC). Master and Ph.D. in Psychology from the Federal University of Rio Grande do Norte. Adjunct Professor in the Department of Psychology at UFC. Collaborating professor in the Graduate Program in Psychology at UFC. Coordinator of PASÁRGADA.

**Mariana Fraga Soares**

Holds a degree in Psychology from the Federal University of Ceará. Currently works as a psychologist at the Social Assistance Reference Center (CRAS) in the municipality of Cascavel-CE.

**Marinara Nobre Paiva**

Psychologist graduated from Luciano Feijão College (FLF) and Master in Psychology and Public Policies from the Federal University of Ceará. Member of the Laboratory of Practices and Research in Psychology and Education (LAPPSIE). Works as a psychologist at the Damião Ximenes Lopes Psychosocial Care Center (CAPS II) for the Municipal Government of Sobral. Lecturer in the Psychology course at Anhanguera College, Sobral campus.

**Marta Clarice Nascimento Oliveira**

Psychology undergraduate at the Federal University of Ceará. Member of PASÁRGADA. Member of VIESES. Collaborator in the Extension Project/Secult-Federal University of Ceará “Insurgent Arts: Colectivizing Resistances”.

**Mayara Ruth Nishiyama Soares**

Psychology graduate from the Federal University of Ceará (UFC). Master’s student in Psychology at UFC. CAPES scholarship holder. Member of LAPSUS and VIESES.

**Milena Araújo Bezerra**

Psychology undergraduate at the Federal University of Ceará. Psychology intern at the Municipal Education Department of Fortaleza (SME). Member of VIESES-Federal University of Ceará.

**Milena Assunção Procópio Barbosa**

Psychology graduate from the Federal University of Ceará (UFC). Specialist in Educational Psychology and Master’s student in the Professional Graduate Program in Psychology and Public Policies (UFC).

**Morena Simonetti Gomes Maciel**

Master’s student in Psychology at the Federal University of Ceará (UFC). Psychology graduate from UFC (2018).

**Myrella Raissa Caetano Linhares**

Psychologist graduated from the Federal University of Ceará.

**Nara Maria Forte Diogo**

Psychologist, Master in Psychology, and Ph.D. in Education (Federal University of Ceará). Professor in the Psychology course in Fortaleza and the Professional Master’s in Psychology and Public Policies at the Federal University of Ceará, Sobral campus. Deputy Coordinator of Locus, the project “Ancestralidades: ancestral soul experiences across generations” and the project “Quilombolar: remaining black at the university.”

**Natália Matos de Souza**

Psychology undergraduate at the Federal University of Ceará. Member of PASÁRGADA and VIESES. Collaborator in the Extension Project/PREX-Federal University of Ceará “Boundless Stories”.

**Natália Santos Marques**

Psychologist (Federal University of Ceará), Master in Psychology (Federal University of Pará), and Ph.D. in Experimental Psychology (USP). Professor in the undergraduate Psychology course and the Professional Master’s in Psychology and Public Policies at the Federal University of Ceará, Sobral campus.

**Nayana Rios Nunes da Silva**

Social Worker graduated from the State University of Ceará (UECE) and Master in Psychology and Public Policies from the Federal University of Ceará. Member of the Laboratory of Practices and Research in Psychology and Education (LAPPSIE). Works as a management analyst for nine years in the Human Resources Management Department at the Autonomous Water and Sewage Service (Saae) of Sobral.

**Pamella Beserra de Melo**

Psychologist (State University of Ceará), Master in Psychology (Federal University of Ceará), and Ph.D. candidate in Psychology at the Federal University of Rio Grande do Norte.

**Quitéria Alves Melo**

Psychologist and Master in Psychology and Public Policies from the Federal University of Ceará. Trained in Historical-Cultural Clinical Psychology. Member of the Laboratory of Practices and Research in Psychology and Education (LAPPSIE). Works in Clinical Psychology and Academic Work Advisory.

**Renata Guimarães de Carvalho**

Professor in the Professional Master’s in Psychology and Public Policies and the Psychology course at the Federal University of Ceará, Sobral campus, specializing in social psychology of work and organizations. Coordinator of the Laboratory of Studies on Health and Subjectivity at Work (LESSAT).

**Ricardo Pinheiro Maia Júnior**

Psychoanalyst, Psychology graduate and Master in Psychology from UNIFOR. Associate member of CLIO - Psychoanalysis Association. Currently a Ph.D. candidate in Psychology at the Federal University of Ceará and extensionist for the CEPC Extension Program.

**Rita Helena Sousa Ferreira Gomes**

Ph.D. in Philosophy from the Federal University of Minas Gerais (UFMG - 2007). Postdoctoral from Simon Fraser University (2015). Professor at the Federal University of Ceará (UFC), Sobral campus. Professor in the Professional Master's in Arts (PROFARTES/UFC). Professor in the Professional Master's in Psychology and Public Policies (UFC). Member of the PESQUISAMUS research group.

**Rogério da Costa Araújo**

Psychologist from the Federal University of Ceará. Advisor for the Right to the City at the Herbert de Souza Life Defense Center.

**Tadeu Lucas de Lavor Filho**

Psychologist (CRP 11/16.666). Ph.D. in Psychology from the Federal University of Ceará. Member of LAPSUS. Psychology professor at Vale do Salgado University Center (UNIVS).

**Thamila Cristina dos Santos da Silva**

Visual artist and psychologist. Master in Psychology and Public Policies from the Federal University of Ceará, Sobral campus.

**Vinicius Nogueira Lopes**

Psychology undergraduate at the Federal University of Ceará. Extension scholarship holder for the PASÁRGADA program.

**Vitor Batista de Melo**

Psychology undergraduate at the Federal University of Ceará. Member of the Maquinarias extension project: childhoods in invention and VIESES.

**Vitória Brandão de Lima Borges**

Dentistry undergraduate at the Fametro University Center, Fortaleza campus.

**Viktoria Braga Leite**

Psychology student at the Federal University of Ceará. Postgraduate in Public and Family Health from the University of Quixeramobim (Uniq). Extensionist for LESSAT.

**Vládia Jamile dos Santos Jucá**

Professor in the Department of Psychology and the Graduate Program in Psychology at the Federal University of Ceará (UFC). Psychologist from UFC (1996), Master in Communication and Contemporary Culture from the Federal University of Bahia (UFBA - 1999), Ph.D. in Collective Health from UFBA (2003). Postdoctoral in Psychoanalytic Theory from the Federal University of Minas Gerais (2016).

**Zulmira Áurea Cruz Bomfim**

Psychology graduate from the Federal University of Ceará (UFC - 1985), Master in Social and Personality Psychology from the University of Brasília (1990), and Ph.D. in Psychology (Social Psychology) from the Pontifical Catholic University of São Paulo (2003). Specialist in socio-environmental intervention and researcher in Public Space and Urban Regeneration from the University of Barcelona (2001). Postdoctoral in Environmental Psychology from the University of Coruña, Spain (2011). Full Professor at UFC in undergraduate and graduate programs.
